### ISSUE TITLE
help request: if request latency could lower than upstream latency?

### ISSUE THREAD

**Issue by jujiale** [apache/apisix#10606] opened 2023-12-06 10:19 UTC
### Description

hello:
  I find in our prd apisix server, in grafana, the request latency is lower than  upstream latency ,such as the following picture, I want to know if have any scenarios could result in such situation.

as I find in logutil.lua
the request latency calculated by **ngx.now() - ngx.req.start_time()** while upstream_latency is **$upstream_response_time**, so why the follwing picture's problem is occured.

need your help, thanks a  lot.

![image](https://github.com/apache/apisix/assets/48037235/6ed596d5-4256-4300-b76f-ca876f5c3d61)

### Environment

- APISIX version (run `apisix version`):2.12.0
- Operating system (run `uname -a`):3.10.0-1160.71.1.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jujiale** [comment] 2023-12-06 10:23
we modify the prometheus DEFAULT_BUCKETS
 local DEFAULT_BUCKETS = {0.005, 0.02, 0.10, 0.5, 1, 3}

**Comment by shreemaan-abhishek** [comment] 2023-12-06 11:00
this is a known issue and we have not been able to get to the root cause of it

**Comment by shreemaan-abhishek** [comment] 2023-12-06 11:22
can you confirm if you haven't changed `proxy_request_buffering` and `proxy_buffering`?

**Comment by wklken** [comment] 2023-12-06 12:25
https://github.com/apache/apisix/issues/5146#issuecomment-928919399

**Comment by jujiale** [comment] 2023-12-07 02:36
> can you confirm if you haven't changed `proxy_request_buffering` and `proxy_buffering`?

yes, I contact with my collegue, `proxy_request_buffering` and `proxy_buffering` not changed.

**Comment by jujiale** [comment] 2023-12-07 02:40
> [#5146 (comment)](https://github.com/apache/apisix/issues/5146#issuecomment-928919399)

thanks for your guide, I have read it. but in my case, but in my case, the upstream latency is **much bigger** than request latency, I guess is not the same reason.

**Comment by jujiale** [comment] 2023-12-07 03:23
> this is a known issue and we have not been able to get to the root cause of it

hello，I want to konw if other issues have suffered the similar situation, if you konw, please refer it to me, thanks a lot

**Comment by shreemaan-abhishek** [comment] 2023-12-07 05:56
this looks like a similar incident: https://the-asf.slack.com/archives/CUC5MN17A/p1696841941644229

**Comment by shreemaan-abhishek** [comment] 2023-12-07 07:16
comment your email I'll invite you to slack.

**Comment by jujiale** [comment] 2023-12-07 07:17
> comment your email I'll invite you to slack.

my email address:    jujiale1218@outlook.com

**Comment by jujiale** [comment] 2023-12-07 07:28
> https://the-asf.slack.com/archives/CUC5MN17A/p1696841941644229

now, I could access it. thanks a lot

**Comment by shreemaan-abhishek** [comment] 2024-01-23 10:15
I hope your query has been resolved. I will close this issue for now.

**Closed by shreemaan-abhishek** 2024-01-23 10:15 UTC
Labels: discuss
