### ISSUE TITLE
Prometheus metrics support view attribute config like route..., not all of them.

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix#7325] opened 2022-06-24 14:39 UTC
### Description

When the  route's number great than 1000+, the `/prometheus` endpiont and prometheus plugin got many error and not work well.  the metrics number may huge than what we can collected.

Need some config for metrics view, can do something like `opentelemetry metrics view` with view attribute's config.
```
code | upstream 服务返回的 HTTP 状态码。
-- | --
route | 请求匹配的 route 的 route_id，未匹配，则默认为空字符串。
matched_uri | 请求匹配的 route 的 uri，未匹配，则默认为空字符串。
matched_host | 请求匹配的 route 的 host，未匹配，则默认为空字符串。
service | 与请求匹配的 route 的 service_id。当路由缺少 service_id 时，则默认为 $host。
consumer | 与请求匹配的 consumer 的 consumer_name。未匹配，则默认为空字符串。
node | 命中的 upstream 节点 ip。
```

BTW, is there any config i can set, enable the prometheus's plugins, and make the route's level metrics not collector?

**Comment by spacewander** [comment] 2022-06-26 12:41
> BTW, is there any config i can set, enable the prometheus's plugins, and make the route's level metrics not collector?

If the `prometheus` plugin is not set in the route, the route's metrics won't be collected.

> Need some config for metrics view, can do something like opentelemetry metrics view with view attribute's config.

Similar to https://github.com/apache/apisix/issues/4273?

**Comment by xuminwlt** [comment] 2022-06-26 13:04
> > BTW, is there any config i can set, enable the prometheus's plugins, and make the route's level metrics not collector?
> 
> If the `prometheus` plugin is not set in the route, the route's metrics won't be collected.
> 
> > Need some config for metrics view, can do something like opentelemetry metrics view with view attribute's config.
> 
> Similar to #4273?

YES, so some label we do not need to collect. we can calculate a constant number of the metrics.

**Comment by spacewander** [comment] 2022-06-26 14:03
Are you willing to work on it?

**Comment by spacewander** [comment] 2022-06-28 05:53
Duplicate of #4273

**Closed by spacewander** 2022-06-28 05:53 UTC
