### ISSUE TITLE
bug: lua-protobuf dependecy problem and segfault

### ISSUE THREAD

**Issue by fatihusta** [apache/apisix#9683] opened 2023-06-16 18:25 UTC
### Current Behavior

Apisix-3.2.0 depends [lua-protobuf-0.4.1](https://github.com/apache/apisix/blob/ff0a0ba3a111ffb95d9c8539cfefaeed3b50a960/rockspec/apisix-3.2.0-0.rockspec#LL49C16-L49C16)  and also [opentelemetry-lua-0.2-3](https://github.com/apache/apisix/blob/ff0a0ba3a111ffb95d9c8539cfefaeed3b50a960/rockspec/apisix-3.2.0-0.rockspec#L76) version.  But Opentelemetry-lua depends [lua-protobuf-0.3.3](https://github.com/yangxikun/opentelemetry-lua/blob/2ea1e8117c5824eef684b12d8cb0cd0c30743c84/rockspec/opentelemetry-lua-0.2-3.rockspec#L15).

also [grpc-client-nginx-module](https://github.com/api7/grpc-client-nginx-module/blob/13b3d4b823b45edca26f68b8d1b2679bed135762/grpc-client-nginx-module-dev-0-0.rockspec#LL30C14-L30C14) depends lua-protobuf-0.3.4.

Those two lua-protobuf packages are installing during the package build. but just lua-protobuf-0.3.3 appends into the deb package.
```
-rwxr-xr-x   92864 2023-06-16 17:19 /usr/local/apisix/deps/lib/lua/5.1/pb.so
-rwxr-xr-x   88216 2023-06-16 17:20 /usr/local/apisix/deps/lib/lua/5.1/lua_protobuf_0_3_3_1-pb.so
```

Segfault error came when I reload the apisix in this state.
I compiled lua-protobuf-0.4.1 manually and I copied the "pb.so" to /usr/local/apisix/deps/lib/lua/5.1/pb.so here. I didn't see the problem.

What is the correct version of lua-protobuf?

### Error Logs

```
[Thu May 18 10:53:14 2023] Code: 89 fd 53 48 8d 5f 18 48 89 df 48 83 ec 10 64 48 8b 04 25 28 00 00 00 48 89 44 24 08 31 c0 48 89 e6 e8 36 cf ff ff 85 c0 74 0a <48> 8b 04 25 10 00 00 00 0f 0b 48 8b 7d 28 4c 8d 65 30 e8 7b c4 ff
[Thu May 18 10:53:14 2023] Code: 89 fd 53 48 8d 5f 18 48 89 df 48 83 ec 10 64 48 8b 04 25 28 00 00 00 48 89 44 24 08 31 c0 48 89 e6 e8 36 cf ff ff 85 c0 74 0a <48> 8b 04 25 10 00 00 00 0f 0b 48 8b 7d 28 4c 8d 65 30 e8 7b c4 ff
[Thu May 18 10:53:14 2023] openresty[108026]: segfault at 10 ip 00007fb30f0e111e sp 00007ffc5a09ad50 error 4 in pb.so[7fb30f0dd000+d000]
[Thu May 18 10:53:14 2023] Code: 89 fd 53 48 8d 5f 18 48 89 df 48 83 ec 10 64 48 8b 04 25 28 00 00 00 48 89 44 24 08 31 c0 48 89 e6 e8 36 cf ff ff 85 c0 74 0a <48> 8b 04 25 10 00 00 00 0f 0b 48 8b 7d 28 4c 8d 65 30 e8 7b c4 ff
[Thu May 18 10:53:14 2023] openresty[108024]: segfault at 10 ip 00007fb30f0e111e sp 00007ffc5a09ad50 error 4 in pb.so[7fb30f0dd000+d000]
[Thu May 18 10:53:14 2023] Code: 89 fd 53 48 8d 5f 18 48 89 df 48 83 ec 10 64 48 8b 04 25 28 00 00 00 48 89 44 24 08 31 c0 48 89 e6 e8 36 cf ff ff 85 c0 74 0a <48> 8b 04 25 10 00 00 00 0f 0b 48 8b 7d 28 4c 8d 65 30 e8 7b c4 ff
[Thu May 18 10:53:14 2023] openresty[108035]: segfault at 10 ip 00007fb30f0e111e sp 00007ffc5a09ad50 error 4 in pb.so[7fb30f0dd000+d000]
[Thu May 18 10:53:14 2023] Code: 89 fd 53 48 8d 5f 18 48 89 df 48 83 ec 10 64 48 8b 04 25 28 00 00 00 48 89 44 24 08 31 c0 48 89 e6 e8 36 cf ff ff 85 c0 74 0a <48> 8b 04 25 10 00 00 00 0f 0b 48 8b 7d 28 4c 8d 65 30 e8 7b c4 ff
[Thu May 18 10:53:14 2023] Pid 108031(openresty) over core_pipe_limit
[Thu May 18 10:53:14 2023] Skipping core dump
[Thu May 18 10:53:14 2023] Pid 108045(openresty) over core_pipe_limit
[Thu May 18 10:53:14 2023] Skipping core dump
[Thu May 18 10:53:14 2023] Pid 108042(openresty) over core_pipe_limit
[Thu May 18 10:53:14 2023] Skipping core dump
[Thu May 18 10:53:14 2023] Pid 108027(openresty) over core_pipe_limit
[Thu May 18 10:53:14 2023] Skipping core dump
[Thu May 18 10:53:14 2023] Pid 108032(openresty) over core_pipe_limit
[Thu May 18 10:53:14 2023] Skipping core dump
[Thu May 18 10:53:14 2023] Pid 108044(openresty) over core_pipe_limit
[Thu May 18 10:53:14 2023] Skipping core dump

```

### Steps to Reproduce

`kill -HUP $(ps aux | grep openresty | grep -v grep | awk '{print $2}')`  execute this command more then one.

Look at the syslog or dmesg logs

`dmesg --time-format=iso | grep segfault`

Note: Wait the worker process shutting down.

`ps aux  | grep nginx | grep shut | grep -v grep`

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): Linux apisix 5.19.0-1025-lowlatency 26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May 23 13:54:47 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment] 2023-06-17 14:02
(following this thread)

**Comment by fatihusta** [comment] 2023-06-19 19:58
I guess I found the segfault problem.

The Problem is came from missing compiler flags.(Speccially `-fPIC` flag.) I added these flags into my script and compiled again. After that I replaced original pb.so with new pb.so during the packaging. The problem is solved. So I realized to why my manually compiled pb.so worked.
`CFLAGS="-fPIC -Wall -Wextra" LIBFLAGS="-shared"` 

Could you please verify this solution?

Note: The Flags are copied from [lua-protobuf](https://github.com/starwing/lua-protobuf) original project.


```sh
CWD=/root/pkgs/apisix/apisix-3.2.0
APISIX_BASE_VER=3.2.0
APISIX_ITERATION=0

# output => 0.4.1
LUA_PROTOBUF_VER=$(grep -oP 'lua-protobuf.*=.*\K(\d+.\d+.\d+)(?=")' ${CWD}/rockspec/apisix-${APISIX_BASE_VER}-${APISIX_ITERATION}.rockspec)


git clone --depth 1 --branch ${LUA_PROTOBUF_VER} https://github.com/starwing/lua-protobuf.git ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}

cp -v ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-0.4.0-1.rockspec \
               ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec

sed -i "s/^version.*=.*/version = \"${LUA_PROTOBUF_VER}-1\"/" \
                ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec
sed -i "s/tag.*=.*/tag = \"$(LUA_PROTOBUF_VER)\"/" \
                ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec

cd ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}
luarocks make ./rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec \
               --local \
               --tree=${LUA_DEPS_DIR_TMP} \
               CFLAGS="-fPIC -Wall -Wextra" LIBFLAGS="-shared"

```

**Comment by shreemaan-abhishek** [comment] 2023-06-21 06:35
> The Problem is came from missing compiler flags.(Speccially -fPIC flag.) I added these flags into my script and compiled again. After that I replaced original pb.so with new pb.so during the packaging. The problem is solved. So I realized to why my manually compiled pb.so worked.

Do you mean to say APISIX is packaged incorrectly? 🤔

**Comment by fatihusta** [comment] 2023-06-21 08:57
> > The Problem is came from missing compiler flags.(Speccially -fPIC flag.) I added these flags into my script and compiled again. After that I replaced original pb.so with new pb.so during the packaging. The problem is solved. So I realized to why my manually compiled pb.so worked.
> 
> Do you mean to say APISIX is packaged incorrectly? 🤔

yes.

**Comment by shreemaan-abhishek** [comment] 2023-06-23 09:19
@fatihusta I tried reproducing this error however I did not encounter any segfault.

**Comment by fatihusta** [comment] 2023-06-24 21:20
I'm not sure why you didn't see this issue. But I saw this issue more than 10 servers. And I fixed that way.

By the way what do you think different versions of lua-protobuf?

**Comment by shreemaan-abhishek** [comment] 2023-06-25 03:22
I have an arm64-based machine so that might be the reason why I didn't find any segfault. That said, I don't think there is any method to have control over which version of a dependency is packaged with apisix or how a particular dependency is being built while packaging or using APISIX. WDYT?

**Comment by Sn0rt** [comment] 2023-09-18 03:41
@fatihusta hi. we can't reproduce this issue, can you provider the clean steps for reproduce ?

**Comment by shreemaan-abhishek** [comment] 2023-11-17 04:43
@fatihusta did you encounter this bug on apisix running on docker/kubernetes?

**Comment by shreemaan-abhishek** [comment] 2023-11-17 04:44
APISIX doesn't yet support `low latency` kernel. Could you please try to reproduce this on standard linux kernel?

**Comment by fatihusta** [comment] 2023-11-17 07:11
Hi,
We are using apisix on bare metal and kvm based virtual machines. I saw this case on vm.

I will try soon to reproduce this bug on generic kernel?

By the way what is the proplem on low latency kernel?

**Comment by shreemaan-abhishek** [comment] 2023-11-17 09:27
> By the way what is the proplem on low latency kernel?

My bad, I shouldn't say "APISIX doesn't yet support low latency kernel". Rather, the CI of APISIX doesn't use low latency kernel hence the consistent behaviour of apisix isn't guaranteed.

**Comment by fatihusta** [comment] 2023-11-19 21:10
Here is video for reproduce. It looks actual problem is gcc optimization flag.(-O2)



https://github.com/apache/apisix/assets/11256228/851a084b-aab6-4948-a43b-697446880396



Reproduce script
```sh
CWD=/root/
LUA_PROTOBUF_VER=0.4.1
LUA_DEPS_DIR_TMP=${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/tmp

# apt install -y liblua5.1-0-dev luarocks gcc

[ ! -d "${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}" ] && \
    git clone --depth 1 --branch ${LUA_PROTOBUF_VER} https://github.com/starwing/lua-protobuf.git ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}

mkdir -p ${LUA_DEPS_DIR_TMP}

cp -v ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-0.4.0-1.rockspec \
               ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec

sed -i "s/^version.*=.*/version = \"${LUA_PROTOBUF_VER}-1\"/" \
                ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec
sed -i "s/tag.*=.*/tag = \"${LUA_PROTOBUF_VER}\"/" \
                ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec


rm -rf ${LUA_DEPS_DIR_TMP}
rm -vrf ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/pb.o ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}/pb.so

cd ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER}

case $1 in
    segfault)
        luarocks make ./rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec \
           --local \
           --tree=${LUA_DEPS_DIR_TMP}
    ;;
    *|fix) # fixes
        luarocks make ./rockspecs/lua-protobuf-${LUA_PROTOBUF_VER}-1.rockspec \
           --local \
           --tree=${LUA_DEPS_DIR_TMP} \
	   CFLAGS="-fPIC -Wall -Wextra" LIBFLAGS="-shared"      # Overwrite CFLAGS
esac

find ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER} -type f -name '*pb.so' -exec md5sum {} \;
printf '\n'
find ${CWD}/lua-protobuf-${LUA_PROTOBUF_VER} -type f -name '*pb.so' -exec ls -l {} \;
printf '\n'
printf 'Copying...\n'
cp -v ${LUA_DEPS_DIR_TMP}/lib/lua/5.1/pb.so /usr/local/apisix/deps/lib/lua/5.1/pb.so
```

**Comment by shreemaan-abhishek** [comment] 2023-11-22 06:22
I was able to repro this issue but this is a problem to be fixed in upstream repo.

however, if I try to install manually using `luarocks install lua-protobuf` I can see the appropriate flags being used as-is:

```bash
gcc -O2 -fPIC -I/usr/local/include -c pb.c -o pb.o
gcc  -shared -o pb.so pb.o
```

![image](https://github.com/apache/apisix/assets/61597896/bb51dbc6-26ad-44e9-ba63-91b070554ffc)

So I am not sure what is causing this error given the flags are present anyways.

**Comment by fatihusta** [comment] 2023-11-22 09:40
We should contact to maintainer of luaprotobuf. We can ask What is going on when compiling with -O2 flag.

**Comment by shreemaan-abhishek** [comment] 2023-11-23 04:19
@fatihusta how did you encounter this segfault? Does this segfault introduce any operational anomalies? (example: many requests fail with 500 error)

**Comment by fatihusta** [comment] 2023-11-23 06:49
Apisix randomly restarts because of this segfault. At that time connections are brokes. So yes, we had operational problem.

**Comment by shreemaan-abhishek** [comment] 2023-11-23 07:26
it's very strange that this error has been reported for the first time.

**Comment by shreemaan-abhishek** [comment] 2023-11-27 01:00
Hello I again tried to reproduce this (in order to fix it) in `Alibaba Cloud Elastic Compute Service`

```

**Comment by shreemaan-abhishek** [comment] 2023-11-27 01:01
Hello I again tried to reproduce this (in order to fix it) in `Alibaba Cloud Elastic Compute Service`

```

**Comment by shreemaan-abhishek** [comment] 2023-11-27 01:04
Hello I again tried to reproduce this (in order to fix it) in `Alibaba Cloud Elastic Compute Service`

```
uname -a
Linux protobuf-lib-segault 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
LSB Version:        core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:        Ubuntu
Description:        Ubuntu 22.04.3 LTS
Release:        22.04
Codename:        jammy

apisix version
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.2.1

openresty -v
nginx version: openresty/1.21.4.2
```

I can no longer reproduce this issue on multiple attempts.

**Comment by fatihusta** [comment] 2023-12-09 11:21
> can we close this one?

If you're asking to me, that's fine for me. I already implemented the solution.

**Comment by Sn0rt** [comment] 2023-12-09 12:48
> > can we close this one?
> 
> If you're asking to me, that's fine for me. I already implemented the solution.

good. @shreemaan-abhishek close this one

**Closed** 2023-12-11 02:18 UTC
Labels: bug, can't reproduce
