### ISSUE TITLE
request help: how to create new routing rule matching designated port by vars 【"server_port"】

### ISSUE THREAD

**Issue by BlinglingGirl** [apache/apisix#2621] opened 2020-11-04 06:40 UTC
### Issue description

curl http://192.168.1.149:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "methods": ["GET"],
    "uri": "/",
    "vars": [["server_port", "==", "9081"]],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "192.168.1.149:8182": 1
        }
    }
}'

response 400 Bad Request

### Environment

* apisix version : 2.0
* OS: centos 7

**Comment by spacewander** [comment] 2020-11-04 06:49
Can't reproduce in my side.
Could you provide the error log?

**Comment by BlinglingGirl** [comment] 2020-11-04 06:51
this is my error , this body don't match json style.

**Comment by spacewander** [comment] 2020-11-04 06:52
OK, I will close this issue.

**Closed by spacewander** 2020-11-04 06:52 UTC
Labels: checking
