### ISSUE TITLE
help request: grpc服务请求并发超过200，客户端就会报rpc error: code = Unavailable desc = the connection is draining

### ISSUE THREAD

**Issue by xionghanhan** [apache/apisix#8576] opened 2022-12-27 09:44 UTC
### Description

试了两种情况
1.直接客户端并发调用超过200，不经过网关，不会报这个rpc error: code = Unavailable desc = the connection is draining错误。
2.经过apisix网关转发调用，超过并发200就会报这个rpc error: code = Unavailable desc = the connection is draining错误。
我怀疑是连接池的配置问题，但是我修改连接池的参数，并发的次数还是超过200就会报错，所以很疑惑，期望可以解答一下。

### Environment

1.使用docker部署的apisix。
2.docker部署两个grpc服务
3.镜像版本：apache/apisix:2.12.0-alpine
4.apisix-dashboard配置如下图
![image](https://user-images.githubusercontent.com/79395110/209646751-78456647-49b6-4fb1-80f4-959f2588620b.png)

**Comment by spacewander** [comment] 2022-12-28 06:32
@An-DJ 
Could you take a look? Thanks!

**Comment by An-DJ** [comment] 2022-12-28 06:49
@spacewander plz assign to me.

**Comment by An-DJ** [comment] 2022-12-29 02:39
@xionghanhan Could u please offer the logs after ur test? e.g. `logs/error.log` and `logs/access.log`

**Comment by An-DJ** [comment] 2022-12-29 11:43
@xionghanhan 
Basiclly that problem is caused by the `failfast` of gRPC (https://github.com/grpc/grpc-go/issues/2205).

Apisix supports configuring nginx directly:
https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

So you can set `http2_max_requests 10000` or a larger number in `conf/config.yaml` to solve this like below:

```
nginx_config:
  http_server_configuration_snippet: |
      keepalive_requests 10000;
```

Or try to use `grpc.FailFast(false)` to switch off the failfast, refering https://github.com/grpc/grpc-go/issues/2205.

**Comment by xionghanhan** [comment] 2023-01-04 03:31
OK, thanks.

**Closed** 2023-05-22 14:50 UTC
