### ISSUE TITLE
request help: grpc-transcode plugin converts http/json parameters abnormally

### ISSUE THREAD

**Issue by zhoujun24** [apache/apisix#1991] opened 2020-08-04 13:00 UTC
### Issue description
The grpc-transcode plugin, after the protocol conversion, the parameters obtained by the back-end service are inconsistent with the http request parameters

.proto：
syntax = "proto3";

package cmdb_api;

// The CmdbAPI service definition.
service CmdbAPI {
  rpc GetHostIPs (IPsRequest) returns (IPsReply) {}
}

message UsageTable {
  string usage = 1;
  repeated string secusage = 2;
}

message IPsRequest {
  repeated string region = 1;
  repeated string idc = 2;
  repeated UsageTable usagetables = 3;
}

message IPsReply {
  repeated string ips = 1;
  string message = 2;
}

Add a route:
curl http://127.0.0.1:9080/apisix/admin/routes/10000 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["POST"],
    "uri": "/CmdbAPI/GetHostIPs",
    "service_protocol": "grpc",
    "plugins": {
        "grpc-transcode": {
            "proto_id": "100",
            "service": "cmdb_api.CmdbAPI",
            "method": "GetHostIPs"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:9096": 1
        }
    }
}'

![image](https://user-images.githubusercontent.com/19777017/89294607-5225ce00-d692-11ea-9308-b60959c87de1.png)
![image](https://user-images.githubusercontent.com/19777017/89295060-fdcf1e00-d692-11ea-8b36-28091ed35a47.png)

### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS: CentOS 7.4
* Golang: 1.13  protoc: 3.11.4

**Comment by membphis** [comment] 2020-08-04 16:23
@nic-chen please take a look at this issue

**Comment by nic-chen** [comment] 2020-08-05 02:35
@zhoujun24  could you have a try that use format `form-data` to send request, please ?

**Comment by zhoujun24** [comment] 2020-08-05 06:23
@nic-chen 
![image](https://user-images.githubusercontent.com/19777017/89378607-bf833e80-d726-11ea-9b8e-f83e3f94178a.png)
![image](https://user-images.githubusercontent.com/19777017/89378817-36203c00-d727-11ea-98fa-4df57ddabe3b.png)

The form-data format does not meet our application scenarios

**Comment by nic-chen** [comment] 2020-08-05 14:48
@zhoujun24 

I know where the problem is now. 
Currently only basic data types are supported, and support for complex types needs to be added:
https://github.com/apache/apisix/blob/master/apisix/plugins/grpc-transcode/util.lua#L63

If you are interested in fixing it, welcome to pr, or I will  deal with it on this weekend.

**Comment by zhoujun24** [comment] 2020-08-06 03:20
@nic-chen 
Another question:
The response defined in .proto is a repeated string type. When the backend response data is empty, the http response data becomes {}, which should be []. You can see in the previous Issue description

I am a backend engineer. Although I am interested in APISIX, I have never used Lua. I usually develop projects in C/C++, Go and Python. If I want to fix the problem, I should learn first.

The doc link of the grpc-transcode plugin on the APISIX project homepage is incorrect, it should actually be https://github.com/apache/apisix/blob/master/doc/plugins/grpc-transcode.md

**Comment by membphis** [comment] 2020-08-06 09:40
> The doc link of the grpc-transcode plugin on the APISIX project homepage is incorrect,

can you supply a screen capture? I can not sure which link is wrong.

**Comment by zhoujun24** [comment] 2020-08-08 01:11
@membphis 
It was fixed a few days ago, https://github.com/apache/apisix/pull/1946

**Comment by membphis** [comment] 2020-08-08 02:11
ok, close this issue

**Comment by zhoujun24** [comment] 2020-08-08 04:05
@membphis 
https://github.com/apache/apisix/issues/1991, This bug is not fixed.

![image](https://user-images.githubusercontent.com/19777017/89702006-3ca0f480-d96f-11ea-8b95-aee0ca2a70d9.png)
![image](https://user-images.githubusercontent.com/19777017/89702022-56dad280-d96f-11ea-8378-20491da81a56.png)

**Comment by zhoujun24** [comment] 2020-08-18 02:42
@nic-chen Hello, When will this issue be fixed?
1. The grpc-transcode plugin, after the protocol conversion, the parameters obtained by the back-end service are inconsistent with the http request parameters
2.The response defined in .proto is a repeated string type. When the backend response data is empty, the http response data becomes {}, which should be []. You can see in the previous Issue description

**Closed** 2020-09-24 04:53 UTC
Labels: bug
