### ISSUE TITLE
request help: Consult APISIX about the implementation of DUBBO protocol support

### ISSUE THREAD

**Issue by wind-clothes** [apache/apisix#1536] opened 2020-05-02 03:40 UTC
### Issue description
I would like to consult about the implementation of supporting DUBBO protocol:
1、Support the use of Lua to implement a set of Dubbo protocols and implement most of its client-side functions；
2、Use other languages to implement, and then call the module through Lua；

### Environment

* apisix version (cmd: `apisix version`):
* OS: MacOS

**Comment by moonming** [comment] 2020-05-11 06:23
Now Apache APISIX's support for duddo is based on Tengine's capabilities, so it cannot be controlled using Lua code.
Welcome PR if you want to support Dubbo in Lua land.

**Comment by wind-clothes** [comment] 2020-05-14 02:01
At present, I am not familiar with Tengine's. It is not clear whether he can support the dynamic nature of the service and establish a mapping relationship with our http api.

**Comment by totemofwolf** [comment] 2020-06-09 14:05
please refer this :

http://tengine.taobao.org/document_cn/ngx_http_dubbo_module_cn.html

**Comment by spacewander** [comment] 2021-01-07 11:24
Duplicate of #89?

**Closed** 2021-01-11 01:13 UTC
Labels: enhancement
