### ISSUE TITLE
request help: Apisix have feature like kong strip_path? Thanks 

### ISSUE THREAD

**Issue by pengtaochang** [apache/apisix#3395] opened 2021-01-22 03:52 UTC
### Issue description
Apisix have feature like kong strip_path? Thanks 
### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment] 2021-01-22 04:03
Duplicate of #2208

**Closed by spacewander** 2021-01-22 04:03 UTC
