### ISSUE TITLE
bug: environment variable can not work well in yaml

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#3055] opened 2020-12-15 15:31 UTC
### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS: mac

### Minimal test code / Steps to reproduce the issue
config.ymal
```
etcd:
  prefix: "/apisix${{CLUSTER_PATH}}"
  timeout: 30
```

export and run
```
export CLUSTER_PATH=/TEST
./bin/apisix start
```

The path of plugins is not correct
(etcdctl get --prefix=true /apisix)
```
/apisix${{CLUSTER_PATH}}/plugins
[{"name":"api-breaker"},{"name":"authz-keycloak"},{"name":"basic-auth"},{"name":"batch-requests"},{"name":"consumer-restriction"},{"name":"cors"},{"name":"echo"},{"name":"fault-injection"},{"name":"grpc-transcode"},{"name":"hmac-auth"},{"name":"http-logger"},{"name":"ip-restriction"},{"name":"jwt-auth"},{"name":"kafka-logger"},{"name":"key-auth"},{"name":"limit-conn"},{"name":"limit-count"},{"name":"limit-req"},{"name":"node-status"},{"name":"openid-connect"},{"name":"prometheus"},{"name":"proxy-cache"},{"name":"proxy-mirror"},{"name":"proxy-rewrite"},{"name":"redirect"},{"name":"referer-restriction"},{"name":"request-id"},{"name":"request-validation"},{"name":"response-rewrite"},{"name":"serverless-post-function"},{"name":"serverless-pre-function"},{"name":"sls-logger"},{"name":"syslog"},{"name":"tcp-logger"},{"name":"udp-logger"},{"name":"uri-blocker"},{"name":"wolf-rbac"},{"name":"zipkin"},{"stream":true,"name":"mqtt-proxy"}]
/apisix/TEST/consumers/
init_dir
/apisix/TEST/global_rules/
init_dir
/apisix/TEST/node_status/
init_dir
/apisix/TEST/plugin_metadata/
init_dir
/apisix/TEST/plugins/
init_dir
/apisix/TEST/proto/
init_dir
/apisix/TEST/routes/
init_dir
/apisix/TEST/services/
init_dir
/apisix/TEST/ssl/
init_dir
/apisix/TEST/stream_routes/
init_dir
/apisix/TEST/upstreams/
init_dir

```

### What's the expected result?
```
/apisix${{CLUSTER_PATH}}/plugins
```

->

```
/apisix/TEST/plugins
```

**Comment by nanamikon** [comment] 2020-12-15 15:47
refer to https://github.com/apache/apisix/issues/3017

**Comment by spacewander** [comment] 2020-12-16 00:57
Duplicate of https://github.com/apache/apisix/issues/3017

**Closed by spacewander** 2020-12-16 00:57 UTC
