### ISSUE TITLE
request help: The request header added by A plugin can't be used for B plugin

### ISSUE THREAD

**Issue by silveric10** [apache/apisix#4271] opened 2021-05-19 04:41 UTC
### Issue description
I have two plugins, A and B, plugin A's function is adding a request header, then plugin B can get this header to do other things. But I found that when my code is like this behind: 
funciton _M.rewrite()
    ... ... 
    ngx.req.set_header("header-added-by-plugin-A",  "test_content")
    ngx.log(ngx.DEBUG, core.request.header(ctx, "header-added-by-plugin-A"))
end

The header's value in log file is nil, and plugin B also can't get this header's value. But on the real server, I can get this header. How can I add a request header in plugin A and make it useable for plugin B? Thank you
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* 1.5
* OS (cmd: `uname -a`):
* Linux 93604787a7a1 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* nginx version: openresty/1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* V2
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):
* /usr/bin/luarocks 2.4.2

**Comment by spacewander** [comment] 2021-05-19 05:20
> Request help without environment information will be ignored or closed.

Please fix the Environment section, otherwise we will close this.

**Comment by silveric10** [comment] 2021-05-19 06:00
> > Request help without environment information will be ignored or closed.
> 
> Please fix the Environment section, otherwise we will close this.

Fixed

**Comment by silveric10** [comment] 2021-05-19 06:24
I know, seems that "core.request.header" will only be updated once when it first calling.

**Comment by Firstsawyou** [comment] 2021-05-19 06:28
You need to make sure that the execution priority of plugin A that sets the request header is greater than plugin B. How to set the request header, you can parameter proxy-rewrite plugin: https://github.com/apache/apisix/blob/master/apisix/plugins/proxy-rewrite.lua#L197

**Comment by silveric10** [comment] 2021-05-19 06:45
> You need to make sure that the execution priority of plugin A that sets the request header is greater than plugin B. How to set the request header, you can parameter proxy-rewrite plugin: https://github.com/apache/apisix/blob/master/apisix/plugins/proxy-rewrite.lua#L197
Thanks.
I'm sure that plugin A's priority is greater than plugin B's priority. I think the reason is I called core.request.header(ctx, ...) at the begining of plugin A, and set new header before plugin A return. The function core.request.header() only be update when it's first call, I think here is the code:    
```
 local headers = ctx.headers
 if not headers then
     headers = get_headers()
     ctx.headers = headers
end
```

**Comment by silveric10** [comment] 2021-05-19 06:54
Maybe you can add a flag that we can choose to force update the headers or just use the cached data

**Comment by spacewander** [comment] 2021-05-19 08:06
The problem is already fixed in https://github.com/apache/apisix/pull/2917.
You may need to upgrade your APISIX.

**Closed** 2021-05-19 08:12 UTC
