### ISSUE TITLE
bug: Prometheus exporter sometimes throws 500 error. 

### ISSUE THREAD

**Issue by kaka11chen** [apache/apisix#2866] opened 2020-11-27 02:52 UTC
### Issue description
Prometheus exporter sometimes throws the following 500 error.
![image](https://user-images.githubusercontent.com/1736049/100405190-1037f200-309e-11eb-8e29-92cf83d13bf8.png)

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: CentOS 7

### Minimal test code / Steps to reproduce the issue
Sometimes throws error.

**Comment by spacewander** [comment] 2020-11-27 02:57
Duplicate of https://github.com/apache/apisix/issues/2394

**Closed by spacewander** 2020-11-27 02:57 UTC
