### ISSUE TITLE
docs: add more comments about discovery in config-default.yaml

### ISSUE THREAD

**Issue by tokers** [apache/apisix#7012] opened 2022-05-10 01:43 UTC
### Current State

We only have the configuration snippet in the comments for `dns` and `erueka` discovery types. See https://github.com/apache/apisix/blob/master/conf/config-default.yaml for the details.

### Desired State

But indeed we support more. We need to show all the configuration snippets there. It's friendly for users who want to configure the corresponding service discovery type.

Missing parts:

* Consul KV
* Nacos
* Kubernetes

**Comment by spacewander** [comment] 2022-05-10 04:04
Duplicate of #6969

**Closed by spacewander** 2022-05-10 04:04 UTC
Labels: good first issue, doc
