### ISSUE TITLE
Some Admin APIs' data structure are not unified

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix#6105] opened 2022-01-14 06:22 UTC
### Issue description

apisix admin api 的略微混乱的数据结构
1. 部分接口（e.g. `/apisix/admin/plugin_metadata`/和 `/apisix/admin/global_rules`）中的 `"count"` 字段是`string`，其余admin接口是`int`
2. 同key数据结构不一致，常见的比如 `node.nodes` 无值`{}`,有值`[]`,更奇葩的是`upstream`的`node.nodes[].nodes`,通过接口更新的是`{}`,通过dashboard更新的是`[{},{}]`,就很难受
3. [/apisix/admin/plugins](https://apisix.apache.org/zh/docs/apisix/admin-api#plugin) `/apisix/admin/plugins?all=true` 和`/apisix/admin/plugins/list` 返回风格与其他接口返回数据风格不一致
4. [stand-alone](https://apisix.apache.org/zh/docs/apisix/stand-alone) 模式不支持(也可能没更新文档 ) [/apisix/admin/plugin_configs](https://apisix.apache.org/zh/docs/apisix/admin-api#plugin-config) 接口
5. [stand-alone#配置-plugins](https://apisix.apache.org/zh/docs/apisix/stand-alone#%E9%85%8D%E7%BD%AE-plugins) 文档中描述 `stream: true # stream 插件需要设置 stream 属性为 true` 啥样的插件算是 stream 插件？没法从admin api 相关接口中获得这个标识

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

感觉很多是历史遗留问题，但是希望最好能解决下

### Actual result

以上

### Error log

无

**Comment by anjia0532** [comment] 2022-01-14 06:26
不是大问题，不影响使用。只是看着别扭而已

**Comment by spacewander** [comment] 2022-01-14 07:23
> /apisix/admin/plugins /apisix/admin/plugins?all=true 和/apisix/admin/plugins/list 返回风格与其他接口返回数据风格不一致

Yes, these APIs don't fetch data from etcd, so they are different.

BTW, `/apisix/admin/plugins/list` should be marked as deprecated. 
PR is welcome!

> stand-alone 模式不支持(也可能没更新文档 ) /apisix/admin/plugin_configs 接口

stand-alone mode doesn't have Admin API.

> stand-alone#配置-plugins 文档中描述 stream: true # stream 插件需要设置 stream 属性为 true 啥样的插件算是 stream 插件？没法从admin api 相关接口中获得这个标识

You can get stream plugin list via `/apisix/admin/plugins?all=true&subsystem=stream`. The API doesn't provide room for stream plugins, so we have to use an extra subsystem argument.

**Comment by spacewander** [comment] 2022-01-14 07:40
> 部分接口（e.g. /apisix/admin/plugin_metadata/和 /apisix/admin/global_rules）中的 "count" 字段是string，其余admin接口是int

These resources forget to call `utils.fix_count` in the get method like route: https://github.com/apache/apisix/blob/92ac6d901d2ca23641037c3979a2e988cc024cd1/apisix/admin/routes.lua#L205

Let's fix it in a separate PR!

You may ask why we don't call `fix_count` on all resources. Because not all the resources come from etcd.

**Comment by spacewander** [comment] 2022-01-14 07:45
> 同key数据结构不一致，常见的比如 node.nodes 无值{},有值[],更奇葩的是upstream的node.nodes[].nodes,通过接口更新的是{},通过dashboard更新的是[{},{}],就很难受

Could you provide detailed steps to reproduce it?

It's a bit weird in this case, because both `{}` and `[]` are valid `nodes` values. The array format is preferable, because:
1. it can be PATCHed
2. it is extendable

**Comment by anjia0532** [comment] 2022-01-14 07:51
> > /apisix/admin/plugins /apisix/admin/plugins?all=true 和/apisix/admin/plugins/list 返回风格与其他接口返回数据风格不一致
> 
> Yes, these APIs don't fetch data from etcd, so they are different.
> 
> BTW, `/apisix/admin/plugins/list` should be marked as deprecated. PR is welcome!
> 
> > stand-alone 模式不支持(也可能没更新文档 ) /apisix/admin/plugin_configs 接口
> 
> stand-alone mode doesn't have Admin API.
> 
> > stand-alone#配置-plugins 文档中描述 stream: true # stream 插件需要设置 stream 属性为 true 啥样的插件算是 stream 插件？没法从admin api 相关接口中获得这个标识
> 
> You can get stream plugin list via `/apisix/admin/plugins?all=true&subsystem=stream`. The API doesn't provide room for stream plugins, so we have to use an extra subsystem argument.

In my test `docker apache/apisix:2.9-alpine`  `subsystem=stream` not work.

**Comment by anjia0532** [comment] 2022-01-14 08:03
> > 同key数据结构不一致，常见的比如 node.nodes 无值{},有值[],更奇葩的是upstream的node.nodes[].nodes,通过接口更新的是{},通过dashboard更新的是[{},{}],就很难受
> 
> Could you provide detailed steps to reproduce it?
> 
> It's a bit weird in this case, because both `{}` and `[]` are valid `nodes` values. The array format is preferable, because:
> 
> 1. it can be PATCHed
> 2. it is extendable

> Could you provide detailed steps to reproduce it?

My env `apache/apisix:2.9-alpine`  and `apache/apisix-dashboard:2.8`

ref doc [docs/apisix/admin-api/#request-body-parameters-3](https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters-3) 
`nodes`'s Description:  `Hash table or array. If it is a hash table, the key of the internal element is the upstream machine address list, the format is Address + (optional) Port, where the address part can be IP or domain name, such as 192.168.1.100:80, foo.com:80, etc. The value is the weight of node. If it is an array, each item is a hash table with key host/weight and optional port/priority. The nodes can be empty, which means it is a placeholder and will be filled later. Clients use such an upstream will get 502 response.` means  `{ "ip:port": weight} or [{"host":"", "weight ":1, "port":80}]`

**Comment by spacewander** [comment] 2022-01-16 12:00
> In my test docker apache/apisix:2.9-alpine subsystem=stream not work.

Yes, it is added in 2.10

**Comment by anjia0532** [comment] 2022-01-17 01:52
> > In my test docker apache/apisix:2.9-alpine subsystem=stream not work.
> 
> Yes, it is added in 2.10

Maybe add since version to doc is a better experience?

**Comment by spacewander** [comment] 2022-01-17 08:02
We currently provide multi-version doc on the doc site: https://apisix.apache.org/docs/apisix/2.9/admin-api

> Maybe add since version to doc is a better experience?

We have tried it before, for example in the control-API's doc.
But it's hard to maintain it as new features are added into APISIX very frequently.

**Comment by anjia0532** [comment] 2022-01-17 08:18
> We currently provide multi-version doc on the doc site: https://apisix.apache.org/docs/apisix/2.9/admin-api
> 
> > Maybe add since version to doc is a better experience?
> 
> We have tried it before, for example in the control-API's doc. But it's hard to maintain it as new features are added into APISIX very frequently.

Yes,This is a feasible solution.

**Comment by mangoGoForward** [comment] 2022-01-18 06:39
> 

Is there any works I can do it to improve this issue?

**Comment by mangoGoForward** [comment] 2022-01-18 06:41
> These resources forget to call `utils.fix_count` in the get method like route:
> 
> https://github.com/apache/apisix/blob/92ac6d901d2ca23641037c3979a2e988cc024cd1/apisix/admin/routes.lua#L205
> 
> Let's fix it in a separate PR!
> 
> You may ask why we don't call `fix_count` on all resources. Because not all the resources come from etcd.

Is there any works I can do it to improve this issue?

**Comment by leslie-tsang** [comment] 2022-01-18 06:45
> > These resources forget to call `utils.fix_count` in the get method like route:
> > https://github.com/apache/apisix/blob/92ac6d901d2ca23641037c3979a2e988cc024cd1/apisix/admin/routes.lua#L205
> > 
> > Let's fix it in a separate PR!
> > You may ask why we don't call `fix_count` on all resources. Because not all the resources come from etcd.
> 
> Is there any works I can do it to improve this issue?

AFAIK, not yet, Would you like to submit a PR to fix it ? Thanks.

**Comment by mangoGoForward** [comment] 2022-01-18 06:49
> > > These resources forget to call `utils.fix_count` in the get method like route:
> > > https://github.com/apache/apisix/blob/92ac6d901d2ca23641037c3979a2e988cc024cd1/apisix/admin/routes.lua#L205
> > > 
> > > Let's fix it in a separate PR!
> > > You may ask why we don't call `fix_count` on all resources. Because not all the resources come from etcd.
> > 
> > 
> > Is there any works I can do it to improve this issue?
> 
> AFAIK, not yet, Would you like to submit a PR to fix it ? Thanks.

I'd like to work on this, let's submit a PR.

**Comment by leslie-tsang** [comment] 2022-01-23 13:59
@juzhiyuan Consider solved. Feel free to reopen it if needed.

**Closed** 2022-01-24 02:46 UTC
Labels: enhancement
