### ISSUE TITLE
help request:  plugin failed get schema

### ISSUE THREAD

**Issue by wnz27** [apache/apisix#9083] opened 2023-03-16 06:21 UTC
### Description

i write plugin config
```
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: opentelemetry-req-id-plugin-config
spec:
  plugins:
    - name: request-id # priority 12015
      enable: true
      config:
        disable: false
```
and apisix log：
<img width="1299" alt="截屏2023-03-16 14 19 29" src="https://user-images.githubusercontent.com/12094918/225532014-79a3590a-db72-4891-aa47-8c3620c5e60a.png">

### Environment

- APISIX version (run `apisix version`): 
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua version
3.1.0

- Operating system (run `uname -a`):
Linux apisix-868c87486c-26rm7 4.19.126-1.jdcloud.x86_64 #1 SMP Wed Jun 10 17:06:52 CST 2020 x86_64 GNU/Linux

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wnz27** [comment] 2023-03-16 08:02
but it's take effect , magic......

**Comment by oyiadin** [comment] 2023-03-19 14:30
perhaps duplicate of https://github.com/apache/apisix/issues/8653

**Comment by shreemaan-abhishek** [comment] 2023-12-28 12:02
> but it's take effect , magic......
I will close it then.

**Closed by shreemaan-abhishek** 2023-12-28 12:02 UTC
