### ISSUE TITLE
bug: limit-conn plugin is not as expected

### ISSUE THREAD

**Issue by LoveleeKay** [apache/apisix#9986] opened 2023-08-08 01:35 UTC
### Current Behavior

"plugins": {
    "limit-conn": {
      "burst": 0,
      "conn": 1,
      "default_conn_delay": 0.1,
      "key": "remote_addr",
      "key_type": "var",
      "rejected_code": 503
    }
  }
![image](https://github.com/apache/apisix/assets/35088017/b9b2010d-ee48-4956-8f1b-cf47ccff5840)
![image](https://github.com/apache/apisix/assets/35088017/f407cec3-e981-4e32-a9e7-11f2f3cd41fc)
I thought only one request is can pass, but 2 of 5 passed ,return 200.

### Expected Behavior

only one request is can pass

### Steps to Reproduce

1、config a router on dashboard
2、use jmeter test

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment] 2023-08-08 02:24
> I thought only one request is can pass, but 2 of 5 passed ,return 200.

Probably because those two requests were not concurrent, which software are you using to test this?

**Comment by LoveleeKay** [comment] 2023-08-08 05:18
> > I thought only one request is can pass, but 2 of 5 passed ,return 200.
> 
> Probably because those two requests were not concurrent, which software are you using to test this?

I use jmeter to test this.I also used java thread pool to test this and get the same result.
![image](https://github.com/apache/apisix/assets/35088017/15b3a7a3-606d-4479-8deb-9b8d69fc9d23)

**Comment by shreemaan-abhishek** [comment] 2023-08-09 07:36
@LoveleeKay, I am not familiar with using jmeter, could you please help me with the steps to run the test using jmeter so that I could try to reproduce this isuue.

**Comment by LoveleeKay** [comment] 2023-08-09 09:54
> 

you can use java thread pool to test this too. Just like the photo that i provided. Also i send this http request quickly, twice in one second, it will return 200 twice. Easy to reproduce this isuue.

**Comment by shreemaan-abhishek** [comment] 2023-08-09 10:52
> Also i send this http request quickly, twice in one second,

You cannot produce concurrent HTTP requests by sending HTTP requests _quickly_. 

You can try using the sleep flag in curl to produce concurrent requests:

```bash
curl -i http://127.0.0.1:9080/index.html?sleep=20 &

curl -i http://127.0.0.1:9080/index.html?sleep=20
```

**Comment by LoveleeKay** [comment] 2023-08-09 11:41
> 

thanks for providing a new test method. i find that this is an accidental result. Sometimes can pass two, sometimes can pass only one. Just as below picture.
![image](https://github.com/apache/apisix/assets/35088017/bc2ba2c0-d828-4bb6-84be-f5191c4bb0dc)

**Comment by Revolyssup** [comment] 2023-08-09 12:03
@LoveleeKay limit-conn plugin limit of 1 means that only one request from that particular client(here identified by remote_addr) will be in-flight at a time. You should test it with an endpoint which takes longer to give response because as soon as response is returned another request will be processed. The requests have to be truly parallel for testing. In our tests, we use `ngx.location.capture_multi` to simulate truly parallel requests.

**Comment by shreemaan-abhishek** [comment] 2023-08-09 12:14
You can close this issue if you have no further queries.

**Comment by LoveleeKay** [comment] 2023-08-10 02:22
> You can close this issue if you have no further queries.

Thanks a lot. I have another query. What is difference between limit-conn and limit-req. Through the seIt seems that they have same function?All of them limit the requests, not connections

**Comment by shreemaan-abhishek** [comment] 2023-08-10 03:28
limit-conn limits concurrent requests and limit-req limits requests based on leaky-bucket algorithm.

**Closed** 2023-08-10 05:08 UTC
Labels: question
