### ISSUE TITLE
bug: Least-connection  result is incorrect

### ISSUE THREAD

**Issue by 840963657** [apache/apisix#7088] opened 2022-05-20 01:44 UTC
### Current Behavior

When I test least-connection，I found the result has nothing to do with active connection；**client always visit the node with the largest weight**。
Then I read source code，found apisix use 1/weight to choose node，Not used active connection；
apisix-apisix-balancer-least_conn.lua:

```lua
function _M.new(up_nodes, upstream)
    local servers_heap = binaryHeap.minUnique(least_score)
    for server, weight in pairs(up_nodes) do
        local score = 1 / weight
        -- Note: the argument order of insert is different from others
        servers_heap:insert({
            server = server,
            effect_weight = 1 / weight,
            score = score,
        }, server)
end
```

### Expected Behavior

least-connection should picks the node with the lowest value of `(active_conn + 1) / weight`

### Steps to Reproduce

1.run apisix;
2.create route,add two nodes，The weights of nodes are different；
3.Client initiated request

### Environment

- APISIX version (run `apisix version`):2.13.1
- Operating system (run `uname -a`):Linux localhost.localdomain 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):etcd_version":"3.4.0
- APISIX Dashboard version, if relevant:2.10
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):luarocks 3.8.0

**Comment by tokers** [comment] 2022-05-20 02:03
@tzssangglass @spacewander PTAL.

**Comment by tzssangglass** [comment] 2022-05-20 02:16
@840963657 I think you have a misconception about its implementation， see:https://github.com/apache/apisix/discussions/5548#discussioncomment-1667885

If you think it is a bug, please describe in detail the steps to reproduce it.

**Comment by 840963657** [comment] 2022-05-20 05:43
> 
This is test result,I think id is a bug....
![image](https://user-images.githubusercontent.com/25243232/169458658-bf88d5f8-c654-4bbb-9da3-5cb70ec6f830.png)

**Comment by tzssangglass** [comment] 2022-05-20 08:06
> This is test result,I think id is a bug....

I need you to provide the steps to reproduce this result.

And did you test it on a single APISIX?

**Comment by 840963657** [comment] 2022-05-23 08:20
> > This is test result,I think id is a bug....
> 
> I need you to provide the steps to reproduce this result.
> 
> And did you test it on a single APISIX?

I test it on a single APISIX.
steps:
1.create an upstream service
2.add two nodes on the upstream service and select the least-connection algorithm（The response times of the two nodes are different）
3.create a route and binding the Route to the Upstream
4.The client initiates multiple connection requests

**Comment by tzssangglass** [comment] 2022-05-24 04:10
Here are my replicated test cases


case 1

```
use t::APISIX 'no_plan';

repeat_each(2);
log_level('info');
no_root_location();
worker_connections(1024);
no_shuffle();

add_block_preprocessor(sub {
    my ($block) = @_;

    if (!$block->request) {
        $block->set_value("request", "GET /mysleep?seconds=0.1");
    }

    if ((!defined $block->error_log) && (!defined $block->no_error_log)) {
        $block->set_value("no_error_log", "[error]");
    }

    my $http_config = $block->http_config // <<_EOC_;
    # fake server, only for test
    server {
        listen 1970;
        location / {
            content_by_lua_block {
                ngx.sleep(0.1)
                ngx.say(1970)
            }
        }
    }

    server {
        listen 1971;
        location / {
            content_by_lua_block {
                ngx.sleep(0.5)
                ngx.say(1971)
            }
        }
    }
_EOC_

    $block->set_value("http_config", $http_config);
});

run_tests();

__DATA__

=== TEST 1: same weight
--- config
    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin").test
            local code, body = t('/apisix/admin/upstreams/1',
                 ngx.HTTP_PUT,
                 [[{
                    "nodes": {
                        "127.0.0.1:1970": 1,
                        "127.0.0.1:1971": 10
                    },
                    "type": "least_conn"
                }]]
                )

            if code >= 300 then
                ngx.status = code
                ngx.say(body)
            end

            local code, body = t('/apisix/admin/routes/1',
                 ngx.HTTP_PUT,
                 [[{
                        "uri": "/hello",
                        "upstream_id": "1"
                }]]
                )

            if code >= 300 then
                ngx.status = code
                ngx.say(body)
            end

            local http = require "resty.http"
            local uri = "http://127.0.0.1:" .. ngx.var.server_port
                        .. "/hello"

            local t = {}
            local ports = {}
            for i = 1, 11 do
                local th = assert(ngx.thread.spawn(function(i)
                    local httpc = http.new()
                    local res, err = httpc:request_uri(uri, {method = "GET"})
                    if not res then
                        ngx.log(ngx.ERR, err)
                        return
                    end
                    local port = tonumber(res.body)
                    ports[i] = port
                end, i))
            end
            for i, th in ipairs(t) do
                ngx.thread.wait(th)
            end

            ngx.sleep(1)
            ngx.log(ngx.WARN, "ports : ", require("inspect")(ports))

            table.sort(ports)
            ngx.say(table.concat(ports, ", "))
        }
    }
--- request
GET /t
--- timeout: 15
--- response_body
1970, 1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971
--- no_error_log
[error]
```


case 2:

```
use t::APISIX 'no_plan';

repeat_each(2);
log_level('info');
no_root_location();
worker_connections(1024);
no_shuffle();

add_block_preprocessor(sub {
    my ($block) = @_;

    if (!$block->request) {
        $block->set_value("request", "GET /mysleep?seconds=0.1");
    }

    if ((!defined $block->error_log) && (!defined $block->no_error_log)) {
        $block->set_value("no_error_log", "[error]");
    }

    my $http_config = $block->http_config // <<_EOC_;
    # fake server, only for test
    server {
        listen 1970;
        location / {
            content_by_lua_block {
                ngx.sleep(0.1)
                ngx.say(1970)
            }
        }
    }

    server {
        listen 1971;
        location / {
            content_by_lua_block {
                ngx.sleep(0.5)
                ngx.say(1971)
            }
        }
    }
_EOC_

    $block->set_value("http_config", $http_config);
});

run_tests();

__DATA__

=== TEST 1: same weight
--- config
    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin").test
            local code, body = t('/apisix/admin/upstreams/1',
                 ngx.HTTP_PUT,
                 [[{
                    "nodes": {
                        "127.0.0.1:1970": 1,
                        "127.0.0.1:1971": 10
                    },
                    "type": "least_conn"
                }]]
                )

            if code >= 300 then
                ngx.status = code
                ngx.say(body)
            end

            local code, body = t('/apisix/admin/routes/1',
                 ngx.HTTP_PUT,
                 [[{
                        "uri": "/hello",
                        "upstream_id": "1"
                }]]
                )

            if code >= 300 then
                ngx.status = code
                ngx.say(body)
            end

            local http = require "resty.http"
            local httpc = http.new()
            local uri = "http://127.0.0.1:" .. ngx.var.server_port
                        .. "/hello"

            local t = {}
            local ports = {}
            for i = 1, 11 do
                local res, err = httpc:request_uri(uri)
                local port = tonumber(res.body)
                ports[i] = port
            end

            table.sort(ports)
            ngx.say(table.concat(ports, ", "))
        }
    }
--- request
GET /t
--- timeout: 15
--- response_body
1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971, 1971
--- no_error_log
[error]
```


case 2 is the bug you mentioned, but this is not actually a bug, as you can see in case 1.

The difference between case 1 and case 2 is that case 1 sends the request serially and case 2 sends it concurrently.

When requests are sent serially, the active connection is actually released at the end of each request.

**Comment by hewj901** [comment] 2022-05-25 07:27
the case 2 ,  all the  request with different session（source port is different ）arrive at the 1971 node，that is not expect with least-conn. From the result,that is independent with session or active-connection.

**Comment by hewj901** [comment] 2022-05-25 07:58
from kong: least_conn算法很简单，首选遍历后端集群，比较每个后端的conns/weight，选取该值最小的后端。
如果有多个后端的conns/weight值同为最小的，那么对它们采用加权轮询算法。
from apisix doc: least_conn: 选择 (active_conn + 1) / weight 最小的节点。注意这里的 active connection 概念跟 Nginx 的相同：它是当前正在被请求使用的连接。
but from the test result, that is no relation with actice-conn.

**Comment by tzssangglass** [comment] 2022-05-25 08:01
Hi @hewj901 , do you mean that case 2 is not the same thing as your test result (all requests visit the high weight node)?

> the case 2 , all the request with different session（source port is different ）arrive at the 1971 node，that is not expect with least-conn.

case 2 result is because the request is executed serially, which means that every time APISIX selects a node using the `least_conn` algorithm, active_conn is actually 0, and nodes with high weights are always selected first.

**Comment by tzssangglass** [comment] 2022-05-25 08:32
> but from the test result, that is no relation with actice-conn.

 I updated case 1 (removed port sorting)

```
use t::APISIX 'no_plan';

repeat_each(2);
log_level('info');
no_root_location();
worker_connections(1024);
no_shuffle();

add_block_preprocessor(sub {
    my ($block) = @_;

    if (!$block->request) {
        $block->set_value("request", "GET /mysleep?seconds=0.1");
    }

    if ((!defined $block->error_log) && (!defined $block->no_error_log)) {
        $block->set_value("no_error_log", "[error]");
    }

    my $http_config = $block->http_config // <<_EOC_;
    # fake server, only for test
    server {
        listen 1970;
        location / {
            content_by_lua_block {
                ngx.sleep(0.5)
                ngx.say(1970)
            }
        }
    }

    server {
        listen 1971;
        location / {
            content_by_lua_block {
                ngx.sleep(0.5)
                ngx.say(1971)
            }
        }
    }
_EOC_

    $block->set_value("http_config", $http_config);
});

run_tests();

__DATA__

=== TEST 1: same weight
--- config
    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin").test
            local code, body = t('/apisix/admin/upstreams/1',
                 ngx.HTTP_PUT,
                 [[{
                    "nodes": {
                        "127.0.0.1:1970": 1,
                        "127.0.0.1:1971": 2
                    },
                    "type": "least_conn"
                }]]
                )

            if code >= 300 then
                ngx.status = code
                ngx.say(body)
            end

            local code, body = t('/apisix/admin/routes/1',
                 ngx.HTTP_PUT,
                 [[{
                        "uri": "/hello",
                        "upstream_id": "1"
                }]]
                )

            if code >= 300 then
                ngx.status = code
                ngx.say(body)
            end

            local http = require "resty.http"
            local uri = "http://127.0.0.1:" .. ngx.var.server_port
                        .. "/hello"

            local t = {}
            local ports = {}
            for i = 1, 3 do
                local th = assert(ngx.thread.spawn(function(i)
                    local httpc = http.new()
                    local res, err = httpc:request_uri(uri, {method = "GET"})
                    if not res then
                        ngx.log(ngx.ERR, err)
                        return
                    end
                    local port = tonumber(res.body)
                    ports[i] = port
                end, i))
            end
            for i, th in ipairs(t) do
                ngx.thread.wait(th)
            end

            ngx.sleep(1)
            ngx.say(table.concat(ports, ", "))
        }
    }
--- request
GET /t
--- timeout: 15
--- response_body
1971, 1971, 1970
--- no_error_log
[error]
```

> So case 2 is serially or concurrently?

Correction, case 1 sends the request concurrently and case 2 sends it serially. To test least_conn, I need to base it on case 1.

Let's discuss case 1 based on the above update :
3 requests will be sent, the` least_conn` will also do 3 rounds of selection

round 1:

1970 score: 0(active connection) + 1 / 1 (weight) = 1
1971 score: 0(active connection) + 1 / 2 (weight) = 0.5

select score smaller 1971

round 2:

1970 score: 0(active connection) + 1 / 1 (weight) = 1
1971 score: 1(active connection) + 1 / 2 (weight) = 1

1971 would be chosen even though the score is the same (not discussing it, which is a separate detail)

round 3:

1970 score: 0(active connection) + 1 / 1 (weight) = 1
1971 score: 2(active connection) + 1 / 2 (weight) = 1.5

select score smaller 1970

Based on this analysis, I think there is no problem with `least_conn`, and the implementation is also related to active connection.

**Comment by 840963657** [comment] 2022-05-26 06:17
In case1

**Comment by tzssangglass** [comment] 2022-05-26 15:00
Not familiar with your verification methods. I presume there is a difference between.
1. are the requests sent at the same time (it would be misleading to say concurrent here)?
2. does the upstream service have enough latency for APISIX to record active connections?

**Comment by bin-53** [comment] 2023-04-18 10:03
> > but from the test result, that is no relation with actice-conn.
> 
> I updated case 1
> 
> ```
> use t::APISIX 'no_plan';
> 
> repeat_each(2);
> log_level('info');
> no_root_location();
> worker_connections(1024);
> no_shuffle();
> 
> add_block_preprocessor(sub {
>     my ($block) = @_;
> 
>     if (!$block->request) {
>         $block->set_value("request", "GET /mysleep?seconds=0.1");
>     }
> 
>     if ((!defined $block->error_log) && (!defined $block->no_error_log)) {
>         $block->set_value("no_error_log", "[error]");
>     }
> 
>     my $http_config = $block->http_config // <<_EOC_;
>     # fake server, only for test
>     server {
>         listen 1970;
>         location / {
>             content_by_lua_block {
>                 ngx.sleep(0.5)
>                 ngx.say(1970)
>             }
>         }
>     }
> 
>     server {
>         listen 1971;
>         location / {
>             content_by_lua_block {
>                 ngx.sleep(0.5)
>                 ngx.say(1971)
>             }
>         }
>     }
> _EOC_
> 
>     $block->set_value("http_config", $http_config);
> });
> 
> run_tests();
> 
> __DATA__
> 
> === TEST 1: same weight
> --- config
>     location /t {
>         content_by_lua_block {
>             local t = require("lib.test_admin").test
>             local code, body = t('/apisix/admin/upstreams/1',
>                  ngx.HTTP_PUT,
>                  [[{
>                     "nodes": {
>                         "127.0.0.1:1970": 1,
>                         "127.0.0.1:1971": 2
>                     },
>                     "type": "least_conn"
>                 }]]
>                 )
> 
>             if code >= 300 then
>                 ngx.status = code
>                 ngx.say(body)
>             end
> 
>             local code, body = t('/apisix/admin/routes/1',
>                  ngx.HTTP_PUT,
>                  [[{
>                         "uri": "/hello",
>                         "upstream_id": "1"
>                 }]]
>                 )
> 
>             if code >= 300 then
>                 ngx.status = code
>                 ngx.say(body)
>             end
> 
>             local http = require "resty.http"
>             local uri = "http://127.0.0.1:" .. ngx.var.server_port
>                         .. "/hello"
> 
>             local t = {}
>             local ports = {}
>             for i = 1, 3 do
>                 local th = assert(ngx.thread.spawn(function(i)
>                     local httpc = http.new()
>                     local res, err = httpc:request_uri(uri, {method = "GET"})
>                     if not res then
>                         ngx.log(ngx.ERR, err)
>                         return
>                     end
>                     local port = tonumber(res.body)
>                     ports[i] = port
>                 end, i))
>             end
>             for i, th in ipairs(t) do
>                 ngx.thread.wait(th)
>             end
> 
>             ngx.sleep(1)
>             ngx.say(table.concat(ports, ", "))
>         }
>     }
> --- request
> GET /t
> --- timeout: 15
> --- response_body
> 1971, 1971, 1970
> --- no_error_log
> [error]
> ```
> 
> > So case 2 is serially or concurrently?
> 
> Correction, case 1 sends the request concurrently and case 2 sends it serially. To test `least_conn`, I need to base it on case 1.
> 
> Let's discuss case 1 based on the above update : 3 requests will be sent, the` least_conn` will also do 3 rounds of selection
> 
> round 1:
> 
> 1970 score: 0(active connection) + 1 / 1 (weight) = 1 1971 score: 0(active connection) + 1 / 2 (weight) = 0.5
> 
> select score smaller 1971
> 
> round 2:
> 
> 1970 score: 0(active connection) + 1 / 1 (weight) = 1 1971 score: 1(active connection) + 1 / 2 (weight) = 1
> 
> 1971 would be chosen even though the score is the same (not discussing it, which is a separate detail)
> 
> round 3:
> 
> 1970 score: 0(active connection) + 1 / 1 (weight) = 1 1971 score: 2(active connection) + 1 / 2 (weight) = 1.5
> 
> select score smaller 1970
> 
> Based on this analysis, I think there is no problem with `least_conn`, and the implementation is also related to active connection.
> 
> Note: that the score used above has nothing to do with the `score` in the APISIX implementation code. It's just to explain that `least_conn` works well in your terms.

Please help me with #9325,the least_conn problem,thanks ,sir

**Comment by bin-53** [comment] 2023-04-19 02:03
When I use the least-conn algorithm to select the upstream, if the score is the same, it should use the polling algorithm to select the node, but in my test, this is not the case.(APISIX version (run apisix 2.15-alpine):)
you can see:
![image](https://user-images.githubusercontent.com/131146587/232947388-43829cc4-c5b0-4c90-8b6c-dc6e6c92f985.png)

I've got five nodes, When I use postman to click continuously, it only poll from three nodes, and the other two nodes are never selected. Is there any problem?
And when i use postman to click continuously ， this ‘active_conn ’ should always be 0. According to (active_conn +1) /weigth, we know that they should have the same score。
With the same minimum number of connections, is a normal polling algorithm used or SWRR？
or Is there more detailed documentation on this part? The official documentation is too simple

**Comment by bin-53** [comment] 2023-04-19 03:21
@tzssangglass

**Comment by thor533** [comment] 2023-04-23 02:36
> hi，[zssangglass](https://github.com/tzssangglass)；thanks for your quick reply。 my test result is different with you in the concurrent case ; follow is my test case:
> 
> this is my test network topo for least-conn，the client is jmeter，
> 
> client ------apisix---------servive node（189 and 124 node，two nodes in LAN）
> 
> case1: node 189 : weight 1 ; node 124 : weight 2 sent 20 requests from client to apisix；all the request is concurrent with different session(we capature the packets, so, can confirm this) ; Simultaneously， capature packets with tcpdump in apisix,node 189,124。 finally，we find all the requests arrive at node 124， no packet to node 189。 we repeat the test case muti-times，the result is same. my test case is near to the real case，so why the result is different with yours?

When I use postman to click consecutively, this active_conn should always be 0. According to (active_conn +1) /weigth, we know that they should have the same score。
With the same minimum number of connections, is a normal polling algorithm used or SWRR？

**Comment by Sn0rt** [comment] 2023-07-25 07:50
ok. I will take a look . @moonming can you assign this issus to me .

**Comment by shreemaan-abhishek** [comment] 2023-09-04 11:40
@Sn0rt any updates?

**Comment by shreemaan-abhishek** [comment] 2023-12-29 03:28
I investigated this and I see no problem with the least-conn algorithm. I will close this issue for now.

**Closed by shreemaan-abhishek** 2023-12-29 03:28 UTC
