### ISSUE TITLE
feature:Does apisix can support the protocol of tars

### ISSUE THREAD

**Issue by shoulda** [apache/apisix#1044] opened 2020-01-13 07:30 UTC
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by moonming** [comment] 2020-01-13 07:58
[Tars](https://github.com/TarsCloud/Tars)  is in the TODO list, welcome PR

**Comment by spacewander** [comment] 2020-11-28 05:40
Duplicate of #812

**Closed by spacewander** 2020-11-28 05:40 UTC
