### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by wudj** [apache/apisix#3764] opened 2021-03-05 10:05 UTC
### Environment

* apisix version (cmd: `apisix version`):2.3
* OS (cmd: `uname -a`):Ubuntu 16 LTS
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.31
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):v3.4.13
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. ./bin/apisix start
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
./bin/apisix start
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
nginx: [error] init_by_lua error: /home/souche/apisix2.3/apisix/init.lua:68: pcre jit stack allocation failed
stack traceback:
	[C]: in function 'error'
	/usr/local/openresty/lualib/ngx/re.lua:311: in function 'opt'
	/home/souche/apisix2.3/apisix/init.lua:68: in function 'http_init'
	init_by_lua:9: in main chunk
### What's the expected result?
start successfully

**Comment by Firstsawyou** [comment] 2021-03-05 10:42
You should provide the installation steps of APISIX dependent environment, such as the installation of `openresty, openresty-openssl-xxx`.

**Comment by spacewander** [comment] 2021-03-08 09:10
Duplicate of #3752

**Closed by spacewander** 2021-03-08 09:10 UTC
