### ISSUE TITLE
bug: APISIX3.5 has high memory usage problems

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#10349] opened 2023-10-17 03:56 UTC
### Current Behavior

Since using APISIX3.5, the memory has been growing continuously, as shown in the figure below.
![iShot_2023-10-17_11 48 09](https://github.com/apache/apisix/assets/59631965/be39032f-9574-4c4e-9fbd-b27cd98eb5fb)
Using the slabtop command, you can see that radixtree occupies a high amount of space.
![image](https://github.com/apache/apisix/assets/59631965/e4ac7219-c5fa-4b96-8be1-b5d2fc6516a0)
There is no such problem on APISIX2.9 or APISIX3.3.

### Steps to Reproduce

Freshly install and run APISIX3.5,then use ETCD as data surface.

### Environment

- APISIX version (run `apisix version`):3.5
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment] 2023-10-17 04:35
cc: @kingluo

**Comment by Sn0rt** [comment] 2023-10-17 10:32
thx, you Report. pls assgin to me .

**Comment by Sn0rt** [comment] 2023-10-20 03:54
Stage information:

1. From the current perspective of slab leaks in Linux, it cannot be concluded that APISIX also has memory leaks.
2. APISIX's radixtree-based route matching is completely in user mode and has nothing to do with the kernel data structure radix_tree_node.
3. APISIX is implemented based on NGX. Because ngx has its own memory management, from the perspective of the operating system, the ngx memory has not been released.
4. User feedback The reason why 3.3 APISIX is ok is that the operating system kernel is different. 3.3 runs on the tlinux kernel.

further processing
1. Wait for the user to switch to tlinux and retest.

**Comment by shreemaan-abhishek** [comment] 2023-10-21 03:38
@Sn0rt thanks for the detailed information.

**Comment by Nobilta** [comment] 2023-10-24 02:31
> Stage information:
> 
> 1. From the current perspective of slab leaks in Linux, it cannot be concluded that APISIX also has memory leaks.
> 2. APISIX's radixtree-based route matching is completely in user mode and has nothing to do with the kernel data structure radix_tree_node.
> 3. APISIX is implemented based on NGX. Because ngx has its own memory management, from the perspective of the operating system, the ngx memory has not been released.
> 4. User feedback The reason why 3.3 APISIX is ok is that the operating system kernel is different. 3.3 runs on the tlinux kernel.
> 
> further processing
> 
> 1. Wait for the user to switch to tlinux and retest.

After upgrading the kernel to 5.4.119-19.0009.32, the phenomenon is the same as before. The openresty worker memory keeps growing after receiving traffic. In the same environment as APISIX 3.3, using the same plug-in configuration (different data plane), version 3.5 has a memory leak problem, but version 3.3 works normally.
<img width="1817" alt="357c914aafdb1ed9d33a33ebf0243e6" src="https://github.com/apache/apisix/assets/59631965/2dd0aca8-5a03-442e-8727-f93f296b2413">
![2476bcb94d536ab1c0338042e28f79c](https://github.com/apache/apisix/assets/59631965/13a74c70-5ff5-48b7-b760-68c62c89d252)

**Comment by Nobilta** [comment] 2023-10-24 04:28
> > Stage information:
> > 
> > 1. From the current perspective of slab leaks in Linux, it cannot be concluded that APISIX also has memory leaks.
> > 2. APISIX's radixtree-based route matching is completely in user mode and has nothing to do with the kernel data structure radix_tree_node.
> > 3. APISIX is implemented based on NGX. Because ngx has its own memory management, from the perspective of the operating system, the ngx memory has not been released.
> > 4. User feedback The reason why 3.3 APISIX is ok is that the operating system kernel is different. 3.3 runs on the tlinux kernel.
> > 
> > further processing
> > 
> > 1. Wait for the user to switch to tlinux and retest.
> 
> After upgrading the kernel to 5.4.119-19.0009.32, the phenomenon is the same as before. The openresty worker memory keeps growing after receiving traffic. In the same environment as APISIX 3.3, using the same plug-in configuration (different data plane), version 3.5 has a memory leak problem, but version 3.3 works normally. <img alt="357c914aafdb1ed9d33a33ebf0243e6" width="1817" src="https://user-images.githubusercontent.com/59631965/277531823-2dd0aca8-5a03-442e-8727-f93f296b2413.png"> ![2476bcb94d536ab1c0338042e28f79c](https://user-images.githubusercontent.com/59631965/277531863-13a74c70-5ff5-48b7-b760-68c62c89d252.png)

According to the memory data of the last dump, the largest address space occupied after string processing is the upstream node information related to the use of the traffic-split plugin.The upstream node information that appears in the dump file is all part 1 in the figure, and the node 2 almost does not exist in the dump file. so we suspect whether it is related to the modification of the traffic-split plugin in version 3.5.
![image](https://github.com/apache/apisix/assets/59631965/1b717824-ac33-463f-a5b3-d5114d941a7d)

**Comment by Sn0rt** [comment] 2023-10-31 10:03
Combining your information, I very much suspect that the problem was introduced in 3.4; combined with the changelog, I guess it is caused by the modification of etcd. Can you help me test it? (I tried to reproduce it on centos but failed. )

Use the 3.3 etcd file to replace the 3.5 one. Take a look at wget https://raw.githubusercontent.com/apache/apisix/release/3.3/apisix/core/config_etcd.lua

**Comment by TakiJoe** [comment] 2023-10-31 10:06
> Combining your information, I very much suspect that the problem was introduced in 3.4; combined with the changelog, I guess it is caused by the modification of etcd. Can you help me test it? (I tried to reproduce it on centos but failed. )
> 
> Use the 3.3 etcd file to replace the 3.5 one. Take a look at wget https://raw.githubusercontent.com/apache/apisix/release/3.3/apisix/core/config_etcd.lua

OK, I'll try to reproduce & test it

**Comment by deluxor** [comment] 2023-11-03 17:37
<img width="1019" alt="Screenshot 2023-11-03 at 17 34 09" src="https://github.com/apache/apisix/assets/5440296/8977e316-68b6-4a1a-9b31-be6b785830da">
We also spotted the same issue with the recent update of version 3.5;
Kept rising until OOM

**Comment by monkeyDluffy6017** [comment] 2023-11-03 17:43
@deluxor we are tracking this problem, do you have any more clues?

**Comment by TakiJoe** [comment] 2023-11-20 03:39
Here is the captured flame graphs and memory usage.
![iShot_2023-11-20_11 32 43](https://github.com/apache/apisix/assets/3213636/7b4b54fd-3825-4ad7-97aa-2afe690c4e9a)

![iShot_2023-11-20_11 13 29](https://github.com/apache/apisix/assets/3213636/0bc81cba-131c-4224-9dc9-c186c4c76597)

![iShot_2023-11-20_11 12 46](https://github.com/apache/apisix/assets/3213636/145d6d5d-74bb-4b80-abf2-9260ab8260cb)

![iShot_2023-11-20_11 15 38](https://github.com/apache/apisix/assets/3213636/e841683c-a37d-4da5-8fe8-2478b33fb621)

![apisix-leaks-202311201050](https://github.com/apache/apisix/assets/3213636/c69f2712-1452-44e3-88be-7fdd22e62675)

![apisix-leaks-202311200930](https://github.com/apache/apisix/assets/3213636/816a0e52-de98-4120-a67f-67e3eb3328ef)

**Comment by monkeyDluffy6017** [comment] 2023-12-08 08:52
We have located this problem: https://github.com/apache/apisix/pull/10614, it will affect all versions between 3.4.0 and 3.7.0

**Comment by monkeyDluffy6017** [comment] 2023-12-12 06:44
I will close this proble since it has been fixed

**Closed by monkeyDluffy6017** 2023-12-12 06:44 UTC
Labels: user responded

**Comment by monkeyDluffy6017** [comment] 2023-12-27 01:32
This commit is needed too: https://github.com/apache/apisix/commit/0a85ba4a07fdd58ec01f8deaed568c833fd3717f

**Comment by TakiJoe** [comment] 2023-12-27 08:46
I did a grayscale test in the production environment and it looks fine so far.（apisix3.5 patched with this two fix https://github.com/apache/apisix/pull/10614 
https://github.com/apache/apisix/pull/10671  )

**Comment by zsmlinux** [comment] 2024-10-28 02:54
> Here is the captured flame graphs and memory usage. ![iShot_2023-11-20_11 32 43](https://private-user-images.githubusercontent.com/3213636/284122622-7b4b54fd-3825-4ad7-97aa-2afe690c4e9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM5MjYsIm5iZiI6MTczMDA4MzYyNiwicGF0aCI6Ii8zMjEzNjM2LzI4NDEyMjYyMi03YjRiNTRmZC0zODI1LTRhZDctOTdhYS0yYWZlNjkwYzRlOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDI0NzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGIwOGJiZDllMGFmMjI4YjM1ZjY3NDY2OGYyOWVmYmI4NDY1OTk3ZDU4Yjc1YjY4YzEzYzBkNTg3MTc0M2Q1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2ydikQ_fNau2yvcEvCzEtRSakPKjSxfZt6DBuMSOr3w)
> 
> ![iShot_2023-11-20_11 13 29](https://private-user-images.githubusercontent.com/3213636/284122723-0bc81cba-131c-4224-9dc9-c186c4c76597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM5MjYsIm5iZiI6MTczMDA4MzYyNiwicGF0aCI6Ii8zMjEzNjM2LzI4NDEyMjcyMy0wYmM4MWNiYS0xMzFjLTQyMjQtOWRjOS1jMTg2YzRjNzY1OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDI0NzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZjNGE4Mzg5Y2MzZDIwOTdiNjJiZTlkMTM5OGU5NzIzMWU2NTdmYmRmODFjYjVlNGVmNmVkM2U1YTBjYmNlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.o3KG9HXJIB5F7Y93x9KrJdbBgcnoHrp9ZpbvbJOKS4Q)
> 
> ![iShot_2023-11-20_11 12 46](https://private-user-images.githubusercontent.com/3213636/284122774-145d6d5d-74bb-4b80-abf2-9260ab8260cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM5MjYsIm5iZiI6MTczMDA4MzYyNiwicGF0aCI6Ii8zMjEzNjM2LzI4NDEyMjc3NC0xNDVkNmQ1ZC03NGJiLTRiODAtYWJmMi05MjYwYWI4MjYwY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDI0NzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRmMjhmODA4MDY2YzYwY2M2Zjk1M2E0ZmY2NDE4MWFhZDIxNTgxM2M3MjQyZjhkZTFmNjViOTE3ZjE1MjA1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5mBs1JZt4PkSTeGFLyDM_5V6oPGx_37rJ7J3iNIh7o0)
> 
> ![iShot_2023-11-20_11 15 38](https://private-user-images.githubusercontent.com/3213636/284122797-e841683c-a37d-4da5-8fe8-2478b33fb621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM5MjYsIm5iZiI6MTczMDA4MzYyNiwicGF0aCI6Ii8zMjEzNjM2LzI4NDEyMjc5Ny1lODQxNjgzYy1hMzdkLTRkYTUtOGZlOC0yNDc4YjMzZmI2MjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDI0NzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZjYzVmZGQ1NDY4YzUyNjExNWUzZGE2MTkxMzc2OGZkYWE2MmY5YzM4MmMxMGViZDdlZDVlZDJiZTM3ZGVjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RFsjoFcvv-Csi6EmFOt6Cs9kSdwLY-wGdXlR_sBxbzA)
> 
> ![apisix-leaks-202311201050](https://private-user-images.githubusercontent.com/3213636/284122853-c69f2712-1452-44e3-88be-7fdd22e62675.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM5MjYsIm5iZiI6MTczMDA4MzYyNiwicGF0aCI6Ii8zMjEzNjM2LzI4NDEyMjg1My1jNjlmMjcxMi0xNDUyLTQ0ZTMtODhiZS03ZmRkMjJlNjI2NzUuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDI0NzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFmMzcyYzBiMjlhY2QyOTE3ZjY1YTY0ODgwNGNlNjc5ODIyMTAzYzBlMTk2Y2JkNTAyYzIzZWNhOTM0ODA0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GRT1WFio6rjALJDnY-Rt6tRqXSb11-005O2WHdca6Mo)
> 
> ![apisix-leaks-202311200930](https://private-user-images.githubusercontent.com/3213636/284122934-816a0e52-de98-4120-a67f-67e3eb3328ef.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM5MjYsIm5iZiI6MTczMDA4MzYyNiwicGF0aCI6Ii8zMjEzNjM2LzI4NDEyMjkzNC04MTZhMGU1Mi1kZTk4LTQxMjAtYTY3Zi02N2UzZWIzMzI4ZWYuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDI0NzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I5YTMxZDIyZmZhNzk2MDExNTgxOTIxYzE1ODkxZjU3MjFiMDQ2OWZhNmJhZjk3ZTYzYzJlOGM5MWU5ODA5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Fbp2APM2JorkAb19FSt5q45DTuN5AsrRudz4MjNjipY)

Excute me, could you tell me the steps for how to generate memory flame graph?
