### ISSUE TITLE
feat: response-rewrite plugin response header rewriting supports NGINX variables

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#4086] opened 2021-04-20 09:15 UTC
### Issue description

Background:

Current user feedback that the response-rewrite plug-in response header rewrite does not support NGINX variable mode. If you want to carry some parameters in the request (for example: cookie in the request header) into the response header, then the response-rewrite plug-in is implemented It's impossible.

Purpose:

If the response header of the response-rewrite plug-in supports NGINX variables, then we can achieve the above functions.
I think it is necessary for us to support response-rewrite plug-in response header rewriting to support NGINX variables.

**Comment by spacewander** [comment] 2021-04-22 04:23
Duplicate of #3727

**Closed by spacewander** 2021-04-22 04:23 UTC
