### ISSUE TITLE
chore: give meaningful reply when etcd is not started

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#2892] opened 2020-11-29 12:17 UTC
https://github.com/apache/apisix/blob/296f535d395bdd388f9f2cd2f8a299fc4b946cc6/apisix/cli/etcd.lua#L119-L124

Currently when etcd is not running, starting apisix would return error `got malformed version message: "" from etcd` at `init`, which is meaningless to users. We need to return a human-readable one.

**Comment by spacewander** [comment] 2020-11-29 13:36
Duplicate of https://github.com/apache/apisix/issues/2718

**Closed by spacewander** 2020-11-29 13:36 UTC
Labels: good first issue
