### ISSUE TITLE
bug: skywalking not work when upsteam timeout

### ISSUE THREAD

**Issue by yxudong** [apache/apisix#4301] opened 2021-05-24 15:09 UTC
### Issue description

At present, sw_tracer:finish()  will be called in body_filter_by_lua phase.
But in some case, the http request will not execute body_filter_by_lua phase. so this function will not be called.

Detail: https://github.com/apache/skywalking/issues/7004

Is this function should be called in log_by_lua phase?

### What's the actual result? (including assertion message & call stack if applicable)

The upsteam timeout case not work with skywalking plugin.

### What's the expected result?

The upsteam timeout case could also be work with skywalking plugin.

**Comment by wu-sheng** [comment] 2021-05-24 15:13
Hi @apache/apisix-committers  SkyWalking community needs verification of whether this is the right description, and a correct way to fix

**Comment by membphis** [comment] 2021-05-25 00:33
Please provide a minimal reproducible case, then we can check it

**Comment by tokers** [comment] 2021-05-25 01:43
We may add a flag to check whether the `sw_tracer:finish` was called in the `body_by_lua_filter*` phase, if not, just calling it in `log_by_lua*` phase.

**Comment by wu-sheng** [comment] 2021-05-25 01:48
> We may add a flag to check whether the `sw_tracer:finish` was called in the `body_by_lua_filter*` phase, if not, just calling it in `log_by_lua*` phase.

`log` method should not provide accurate endtime, as far as I know. If the timeout really could cause the issue, then I think we have to make a flag for the status.

**Comment by yxudong** [comment] 2021-05-25 02:21
The specific case is here.

> location = /test {
>     rewrite_by_lua_block {
>         skywalking_tracer:start("upstream service")
>     }
> 
>     proxy_pass http://test_upsteam;
>     proxy_connect_timeout 1;
>     proxy_send_timeout 1;
>     proxy_read_timeout 1;
> 
>     body_filter_by_lua_block {
>         if ngx.arg[2] then
>             skywalking_tracer:finish()
>         end
>     }
> 
>     log_by_lua_block {
>         skywalking_tracer:prepareForReport()
>     }
> }

The proxy_read_timeout config is 1s.
When http://test_upsteam reponse time more than that, nginx will has error log

> upstream timed out (110: Connection timed out) while reading response header from upstream, xxxxxxxxxx

In this case, the http request will not execute body_filter_by_lua phase, and `sw_tracer:finish` function is not be called also.

**Comment by spacewander** [comment] 2021-05-25 03:03
Response without body also causes this problem, like HEAD request's response.

**Comment by wu-sheng** [comment] 2021-05-25 05:12
> Response without body also causes this problem, like HEAD request's response.

Thanks for sharing more cases. What is the recommended fix? Do we have to move this into the `log_by` with a recheck? We have to face an inaccurate end time.

**Comment by spacewander** [comment] 2021-05-25 06:21
My opinion:
1. normal response: keep the current behavior
2. without response (the timed out case pointed by @yxudong): add `finish` call if we haven't called it yet
3. header only response (`HEAD` request, 204 or 304 response): add `finish` call in the header filter phase.

**Comment by wu-sheng** [comment] 2021-05-25 06:23
> My opinion:
> 
> 1. normal response: keep the current behavior
> 2. without response (the timed out case pointed by @yxudong): add `finish` call if we haven't called it yet
> 3. header only response (`HEAD` request, 204 or 304 response): add `finish` call in the header filter phase.

@yxudong Would you work on a patch to SkyWalking nginx agent to do that? We need some code changes rather than only doc change.

cc @dmsolr I think after this, we need to adjust Kong plugin. @spacewander we need to adopt this fix in APISIX too.

**Comment by yxudong** [comment] 2021-05-25 06:34
Ok, I'll try to work on a patch with this according to @spacewander 's opinion.

**Comment by yxudong** [comment] 2021-05-25 12:48
Hi, everyone.

It's seems that there is an easy solution to this problem.
Just change `body_filter_by_lua` phase to `header_filter_by_lua` phase, because `body_filter_by_lua` may not be executed in some case, but `header_filter_by_lua` is always will be executed.
At least, It's work in all the scenarios I can think of after my experiment.

In addition, `sw_tracer:finish` should be called in header_filter_by_lua phase logically, because `header_filter_by_lua` phase is before `body_filter_by_lua` phase.

Does it work this solution?
Or Is there anything I missed.

**Comment by wu-sheng** [comment] 2021-05-25 12:51
Does `header_filter_by_lua` work for timeout?

**Comment by wu-sheng** [comment] 2021-05-25 12:52
You should know, in other SkyWalking agents, there is a config to control collecting HTTP request and response bodies when necessary. It is better to keep `body_filter_by_lua` works in normal cases.

**Comment by yxudong** [comment] 2021-05-25 12:54
Yes, I've already experimented about timeout case.

**Comment by yxudong** [comment] 2021-05-25 13:41
If change `body_filter_by_lua` phase to `header_filter_by_lua` phase is too risk, I submitted a PR about this issue.

https://github.com/apache/skywalking-nginx-lua/pull/85

Add a flag to makesure the `Tracer:finish()` was called.
Please check it.

If it's no problem, I'd like to submitted a PR about Kong plugin and APISIX.

**Comment by spacewander** [comment] 2021-05-25 14:18
> In addition, sw_tracer:finish should be called in header_filter_by_lua phase logically, because header_filter_by_lua phase is before body_filter_by_lua phase.

Calling the `finish` in header_filter_by_lua in a non-head-only response will result in a too-short trace span. Consider the server is serving a 1 GB file, the time when the response finish generating header is quite earlier than generating all the body.

**Comment by yxudong** [comment] 2021-05-25 14:21
> > In addition, sw_tracer:finish should be called in header_filter_by_lua phase logically, because header_filter_by_lua phase is before body_filter_by_lua phase.
> 
> Calling the `finish` in header_filter_by_lua in a non-head-only response will result in a too-short trace span. Consider the server is serving a 1 GB file, the time when the response finish generating header is quite earlier than generating all the body.

Got it. Thank you for reply.

**Comment by wu-sheng** [comment] 2021-06-02 13:27
https://github.com/apache/skywalking-nginx-lua/pull/85 merged. We will need skywalking's next release for APISIX fix.

**Comment by spacewander** [comment] 2021-12-08 06:45
@dmsolr 
Maybe we can create a new release of skywalking-nginx-lua now?

**Comment by wu-sheng** [comment] 2021-12-08 06:54
![image](https://user-images.githubusercontent.com/5441976/145162308-af4de142-2ccc-4581-b93d-1c6d15a01b3c.png)

2 fixes are code related. It is 7 months since last release, if you feel you should, please run for it. If you do that, skywalking-kong 0.1.2 should be released with dependency upgrade.

**Comment by wu-sheng** [comment] 2021-12-17 02:12
@dmsolr Any update about this?

**Comment by dmsolr** [comment] 2021-12-17 02:51
I am sorry for pending long time. I am going to release a version before next week.

**Comment by dmsolr** [comment] 2021-12-17 02:52
I am sorry for pending long time. I am going to release a version before next week.

**Comment by dmsolr** [comment] 2021-12-26 04:43
Hi @yxudong , skywalking-nginx-lua v0.6.0 released. And it is available on luarocks

**Comment by yxudong** [comment] 2021-12-30 06:48
> Hi @yxudong , skywalking-nginx-lua v0.6.0 released. And it is available on luarocks

Got it, Ths.

**Comment by wu-sheng** [comment] 2021-12-30 06:52
Should APISIX upgrade the dependency for the next release?

**Comment by juzhiyuan** [comment] 2021-12-30 14:52
cc @shuaijinchao

**Comment by membphis** [comment] 2021-12-31 01:02
> Hi @yxudong , skywalking-nginx-lua v0.6.0 released. And it is available on luarocks

@dmsolr I think you can submit the PR directly, it is very easy, here is an example: https://github.com/apache/apisix/pull/5971

**Closed** 2021-12-31 03:19 UTC
Labels: bug
