### ISSUE TITLE
request help:  APISIX Can't  Start

### ISSUE THREAD

**Issue by meiping05** [apache/apisix#3290] opened 2021-01-14 08:59 UTC
### Issue description
APISIX can't start

### Environment

* apisix version (cmd: `apisix version`): github master branch
* OS: (cmd: `uname -a`) : macOS Big Sur (11.1)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

### Error Info

run
`./bin/apisix version error`

`lua: error loading module 'socket.core' from file 'apisix/deps/lib/lua/5.1/socket/core.so':
	dlopen(apisix/deps/lib/lua/5.1/socket/core.so, 6): Symbol not found: _luaL_openlib
  Referenced from: apisix/deps/lib/lua/5.1/socket/core.so
  Expected in: dynamic lookup`

**Comment by spacewander** [comment] 2021-01-14 09:03
Duplicate of #3281

**Closed by spacewander** 2021-01-14 09:03 UTC
