### ISSUE TITLE
help request: the metric data provided by "apisix-prometheus plugin" will be reset once apisix restarted

### ISSUE THREAD

**Issue by MoseChen** [apache/apisix#7537] opened 2022-07-26 06:59 UTC
### Description

Once apisix is restarted, the output of 'apisix-prometheus plugin' will be reset.
Do we have a way to store those metrics value and recover them during apisix-restart-window ?
![Image_20220726145356](https://user-images.githubusercontent.com/11345202/180943660-a12eab95-e909-4384-b178-49f52204ce67.png)
 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment] 2022-07-26 10:21
@MoseChen What's the command you use to restart APISIX? If you use `apisix restart` it do reset the Prometheus metrics.

You can use the hot restart way to restart APISIX via sending `SIGUSR2` to APISIX master.

**Comment by spacewander** [comment] 2022-07-26 10:27
Duplicate of https://github.com/apache/apisix/issues/4809

**Comment by spacewander** [comment] 2022-07-28 05:48
Consider solved. Feel free to reopen it if needed.

**Closed by spacewander** 2022-07-28 05:48 UTC
