### ISSUE TITLE
request help: how nodes will be recovered from unhealthy

### ISSUE THREAD

**Issue by yocaning** [apache/apisix#3616] opened 2021-02-20 03:31 UTC
### Issue description
healthy check
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):centos7
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
* apisix-dashboard version, if have:

想问下健康检查标记为 unhealthy的node，在什么条件下才会重新恢复healthy状态，看文档中没有相关信息

**Comment by Firstsawyou** [comment] 2021-02-20 03:37
You can try to configure this property `active.unhealthy.interval`.
You can refer to the attribute description here: https://github.com/apache/apisix/blob/master/doc/health-check.md

**Comment by yocaning** [comment] 2021-02-20 03:46
active.unhealthy.interval 这个是主动监测，passive也适用么，文档中passive没有这个字段

**Comment by yocaning** [comment] 2021-02-20 03:51
> You can try to configure this property `active.unhealthy.interval`.
> You can refer to the attribute description here: https://github.com/apache/apisix/blob/master/doc/health-check.md

active.unhealthy.interval 这个是主动监测，passive也适用么，文档中passive没有这个字段

**Comment by Firstsawyou** [comment] 2021-02-20 04:23
> active.unhealthy.interval 这个是主动监测，passive也适用么，文档中passive没有这个字段

`passive` check does not support `interval`.

**Comment by tokers** [comment] 2021-02-20 05:48
@yocaning `active.unhealthy.interval` is the interval of the active health checker to probe all "unhealthy" nodes, once unhealthy nodes are online again (probes successful for several consecutive times), they will be marked as healthy.

**Comment by tokers** [comment] 2021-02-20 05:50
@Firstsawyou Would you create a document to supplement some details of healthy check. You can create another issue to track it.

**Comment by Firstsawyou** [comment] 2021-02-20 06:42
> @Firstsawyou Would you create a document to supplement some details of healthy check. You can create another issue to track it.

The health check is documented: https://github.com/apache/apisix/blob/master/doc/health-check.md.
I think we can add some details to the existing documents.

**Comment by yocaning** [comment] 2021-02-20 06:47
> several

it does not work ,because no active path to check

**Comment by Firstsawyou** [comment] 2021-02-20 07:21
> > several
> 
> it does not work ,because no active path to check

You should use `active.unhealthy.interval` in active health check.
If it does not work, you should provide the configuration information.

**Comment by yocaning** [comment] 2021-02-20 07:25
> > > several
> > 
> > 
> > it does not work ,because no active path to check
> 
> You should use `active.unhealthy.interval` in active health check.
> If it does not work, you should provide the configuration information.

背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原

**Comment by yocaning** [comment] 2021-02-20 07:26
贴一下我的配置：{
"id": "1",
"update_time": 1613734165,
"upstream": {
"checks": {
"active": {
"unhealthy": {
"interval": 30
},
"concurrency": 10,
"timeout": 1,
"https_verify_certificate": true,
"http_path": "/",
"type": "http"
},
"passive": {
"timeout": 5,
"healthy": {
"http_statuses": [
200,
201
],
"successes": 3
},
"type": "http",
"unhealthy": {
"http_statuses": [
500,
504
],
"timeouts": 3,
"timeout": 5,
"tcp_failures": 1,
"http_failures": 1
}
}
},
"retries": 2,
"nodes": {
"**:8080": 1,
"**:8080": 1
},
"timeout": {
"connect": 3,
"read": 3,
"send": 3
},
"pass_host": "pass",
"hash_on": "vars",
"type": "roundrobin"
},
"methods": [
"PUT",
"GET"
],
"status": 1,
"create_time": 1613722689,
"priority": 0,
"uri": "/cmd"
}

**Comment by Firstsawyou** [comment] 2021-02-20 08:01
> "timeouts": 3,
> "timeout": 5,
> "tcp_failures": 1,
> "http_failures": 1

<img width="356" alt="截屏2021-02-20 下午3 55 37" src="https://user-images.githubusercontent.com/52862365/108588572-e50b2900-7394-11eb-9af7-98928da0f871.png">

There is no `timeout` in the `passive` check. Try to remove the `timeout` attribute.

**Comment by Firstsawyou** [comment] 2021-02-20 08:08
> 背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原

The `passive.healthy.successes` in the `passive` check can restore the unhealthy node.

Because `passive.healthy.successes` means: the upstream node has been successfully detected (defined by passive.healthy.http_statuses) for more than successes times, then the node is set to healthy state.

**Comment by yocaning** [comment] 2021-02-20 09:21
> > 背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原
> 
> The `passive.healthy.successes` in the `passive` check can restore the unhealthy node.
> 
> Because `passive.healthy.successes` means: the upstream node has been successfully detected (defined by passive.healthy.http_statuses) for more than successes times, then the node is set to healthy state.



> @yocaning `active.unhealthy.interval` is the interval of the active health checker to probe all "unhealthy" nodes, once unhealthy nodes are online again (probes successful for several consecutive times), they will be marked as healthy.

我按照你这个方式进行配置，interval:10 每10s确实有探测，但是当我重新启动节点时，就算探测成功，也没有将这个节点标记为healthy状态，也就是依旧不可用

**Comment by yocaning** [comment] 2021-02-20 09:22
> > 背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原
> 
> The `passive.healthy.successes` in the `passive` check can restore the unhealthy node.
> 
> Because `passive.healthy.successes` means: the upstream node has been successfully detected (defined by passive.healthy.http_statuses) for more than successes times, then the node is set to healthy state.

你这个有一个逻辑问题：the upstream node has been successfully detected (defined by passive.healthy.http_statuses) for more than successes times, then the node is set to healthy state.

**Comment by yocaning** [comment] 2021-02-20 09:23
> > 背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原
> 
> The `passive.healthy.successes` in the `passive` check can restore the unhealthy node.
> 
> Because `passive.healthy.successes` means: the upstream node has been successfully detected (defined by passive.healthy.http_statuses) for more than successes times, then the node is set to healthy state.

被动检查被标记为unhealthy的node，不会再去探测了，也就是说the upstream node has been successfully detected (defined by passive.healthy.http_statuses) for more than successes times, then the node is set to healthy state.无从说起

**Comment by yocaning** [comment] 2021-02-20 09:25
文档中关于unhealthy节点的探测有两个配置项："unhealthy": {
"interval": 10,
"http_failures": 2
}, the interval 代表间隔，http_failures代表什么呢，本来就是监测unhealthy状态的节点，是说监测多少次成功就会变成healthy么，但是实际上并不工作，没有生效

**Comment by Firstsawyou** [comment] 2021-02-20 10:59
> 文档中关于unhealthy节点的探测有两个配置项："unhealthy": {
> "interval": 10,
> "http_failures": 2
> }, the interval 代表间隔，http_failures代表什么呢，本来就是监测unhealthy状态的节点，是说监测多少次成功就会变成healthy么，但是实际上并不工作，没有生效

`http_failures` is the number of failed requests to set the target node. If the number of failed checks of the target node is greater than the number set by `http_failures` within the time of `interval`, then the target node will be marked as unhealthy.

**Comment by Firstsawyou** [comment] 2021-02-20 11:02
> 但是实际上并不工作，没有生效

please provide a minimum reproduction step.

**Comment by tokers** [comment] 2021-02-20 11:56
> > > > several
> > > 
> > > 
> > > it does not work ,because no active path to check
> > 
> > 
> > You should use `active.unhealthy.interval` in active health check.
> > If it does not work, you should provide the configuration information.
> 
> 背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原

Actually you cannot only enable passive healthy check, the active one also woks even if you don't configure it.
The below is some snippets of the schema (https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L98).

```
```
![image](https://user-images.githubusercontent.com/10428333/108594555-a20d7d80-73b5-11eb-9891-d2ad386d107f.png)

**Comment by yocaning** [comment] 2021-02-20 13:40
> > 但是实际上并不工作，没有生效
> 
> please provide a minimum reproduction step.

Don't you read the above？i showed my configuration

**Comment by yocaning** [comment] 2021-02-20 13:42
> > > > > several
> > > > 
> > > > 
> > > > it does not work ,because no active path to check
> > > 
> > > 
> > > You should use `active.unhealthy.interval` in active health check.
> > > If it does not work, you should provide the configuration information.
> > 
> > 
> > 背景再描述一下，我选用的是被动检查也就是passive，在某个node被检查成为unhealthy之后，我该如何使其复原
> 
> Actually you cannot only enable passive healthy check, the active one also woks even if you don't configure it.
> The below is some snippets of the schema (https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L98).
> 
> ![image](https://user-images.githubusercontent.com/10428333/108594555-a20d7d80-73b5-11eb-9891-d2ad386d107f.png)

yes，i set it both passive and active ，but still not work，i will show my all config right now

**Comment by yocaning** [comment] 2021-02-20 13:45
`{"id":"1","update_time":1613734165,"upstream":{"checks":{"active":{"healthy":{"interval":3,"successes":2},"unhealthy": { "interval": 10,"http_failures": 2},"concurrency":10,"timeout":1,"https_verify_certificate":true,"http_path":"/status?cmd=6003","type":"http","req_headers": ["Content-Seq:3"]},"passive":{"timeout":5,"healthy":{"http_statuses":[200,201],"successes":3},"type":"http","unhealthy":{"http_statuses":[500,504],"timeouts":3,"tcp_failures":1,"http_failures":1}}},"nodes":{"***:8080":1,"***:8080":1},"timeout":{"connect":3,"read":3,"send":3},"pass_host":"pass","hash_on":"vars","type":"roundrobin"},"methods":["PUT","GET"],"status":1,"create_time":1613722689,"priority":0,"uri":"/cmd"}`

**Comment by Firstsawyou** [comment] 2021-02-22 08:10
Hi, @yocaning  
You need to pay attention to your configuration. The `http_path` of the active health check should be consistent with the uri that provides the service. Secondly, the value of `"timeout":1` is recommended to be set larger.


This is an example, you can refer to it

1、Add a route and enable health check

The 1981 and 1982 ports are healthy, but the 1985 port is unhealthy.

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "id":"1",
    "update_time":1613734165,
    "upstream":{
        "checks":{
            "active":{
                "healthy":{
                    "interval":3,
                    "successes":2
                },
                "unhealthy":{
                    "interval":10,
                    "http_failures":2
                },
                "timeout":10,
                "http_path":"/hello",
                "type":"http",
                "req_headers":[
                    "Content-Seq:3"
                ]
            },
            "passive":{
                "timeout":5,
                "healthy":{
                    "http_statuses":[
                        200,
                        201
                    ],
                    "successes":3
                },
                "type":"http",
                "unhealthy":{
                    "http_statuses":[
                        500,
                        504
                    ],
                    "timeouts":3,
                    "tcp_failures":1,
                    "http_failures":1
                }
            }
        },
        "nodes":{
            "127.0.0.1:1980":1,
            "127.0.0.1:1981":1,
            "127.0.0.1:1985":1
        },
        "timeout":{
            "connect":3,
            "read":3,
            "send":3
        },
        "pass_host":"pass",
        "hash_on":"vars",
        "type":"roundrobin"
    },
    "methods":[
        "PUT",
        "GET"
    ],
    "status":1,
    "create_time":1613722689,
    "priority":0,
    "uri":"/hello"
}'
```

2、Access request and view error.log

```
2021/02/22 15:41:42 [warn] 23035#23035: *66190 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (1/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
2021/02/22 15:41:48 [warn] 23035#23035: *66445 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080

2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1980)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1981)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
```
3、When the 1985 port returned to health and view error.log

```
2021/02/22 15:57:32 [warn] 23035#23035: *107236 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
``

**Comment by yocaning** [comment] 2021-02-24 08:46
> Hi, @yocaning
> You need to pay attention to your configuration. The `http_path` of the active health check should be consistent with the uri that provides the service. Secondly, the value of `"timeout":1` is recommended to be set larger.
> 
> This is an example, you can refer to it
> 
> 1、Add a route and enable health check
> 
> The 1981 and 1982 ports are healthy, but the 1985 port is unhealthy.
> 
> ```shell
> curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "id":"1",
>     "update_time":1613734165,
>     "upstream":{
>         "checks":{
>             "active":{
>                 "healthy":{
>                     "interval":3,
>                     "successes":2
>                 },
>                 "unhealthy":{
>                     "interval":10,
>                     "http_failures":2
>                 },
>                 "timeout":10,
>                 "http_path":"/hello",
>                 "type":"http",
>                 "req_headers":[
>                     "Content-Seq:3"
>                 ]
>             },
>             "passive":{
>                 "timeout":5,
>                 "healthy":{
>                     "http_statuses":[
>                         200,
>                         201
>                     ],
>                     "successes":3
>                 },
>                 "type":"http",
>                 "unhealthy":{
>                     "http_statuses":[
>                         500,
>                         504
>                     ],
>                     "timeouts":3,
>                     "tcp_failures":1,
>                     "http_failures":1
>                 }
>             }
>         },
>         "nodes":{
>             "127.0.0.1:1980":1,
>             "127.0.0.1:1981":1,
>             "127.0.0.1:1985":1
>         },
>         "timeout":{
>             "connect":3,
>             "read":3,
>             "send":3
>         },
>         "pass_host":"pass",
>         "hash_on":"vars",
>         "type":"roundrobin"
>     },
>     "methods":[
>         "PUT",
>         "GET"
>     ],
>     "status":1,
>     "create_time":1613722689,
>     "priority":0,
>     "uri":"/hello"
> }'
> ```
> 
> 2、Access request and view error.log
> 
> ```
> $ curl http://127.0.0.1:9080/hello
> hello 1980
> 
> $ tail -f error.log
> 2021/02/22 15:41:42 [warn] 23035#23035: *66190 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (1/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> 2021/02/22 15:41:48 [warn] 23035#23035: *66445 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> 
> 2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1980)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> 2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1981)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> ```
> 
> 3、When the port of `1985` recovered health and view error.log
> 
> When an unhealthy node is restored to a healthy node, it will be automatically marked as healthy.
> 
> ```
> 2021/02/22 15:57:32 [warn] 23035#23035: *107236 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> ```

thank you ，i‘ll take a try

**Comment by yocaning** [comment] 2021-02-25 08:50
> Hi, @yocaning
> You need to pay attention to your configuration. The `http_path` of the active health check should be consistent with the uri that provides the service. Secondly, the value of `"timeout":1` is recommended to be set larger.
> 
> This is an example, you can refer to it
> 
> 1、Add a route and enable health check
> 
> The 1981 and 1982 ports are healthy, but the 1985 port is unhealthy.
> 
> ```shell
> curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "id":"1",
>     "update_time":1613734165,
>     "upstream":{
>         "checks":{
>             "active":{
>                 "healthy":{
>                     "interval":3,
>                     "successes":2
>                 },
>                 "unhealthy":{
>                     "interval":10,
>                     "http_failures":2
>                 },
>                 "timeout":10,
>                 "http_path":"/hello",
>                 "type":"http",
>                 "req_headers":[
>                     "Content-Seq:3"
>                 ]
>             },
>             "passive":{
>                 "timeout":5,
>                 "healthy":{
>                     "http_statuses":[
>                         200,
>                         201
>                     ],
>                     "successes":3
>                 },
>                 "type":"http",
>                 "unhealthy":{
>                     "http_statuses":[
>                         500,
>                         504
>                     ],
>                     "timeouts":3,
>                     "tcp_failures":1,
>                     "http_failures":1
>                 }
>             }
>         },
>         "nodes":{
>             "127.0.0.1:1980":1,
>             "127.0.0.1:1981":1,
>             "127.0.0.1:1985":1
>         },
>         "timeout":{
>             "connect":3,
>             "read":3,
>             "send":3
>         },
>         "pass_host":"pass",
>         "hash_on":"vars",
>         "type":"roundrobin"
>     },
>     "methods":[
>         "PUT",
>         "GET"
>     ],
>     "status":1,
>     "create_time":1613722689,
>     "priority":0,
>     "uri":"/hello"
> }'
> ```
> 
> 2、Access request and view error.log
> 
> ```
> $ curl http://127.0.0.1:9080/hello
> hello 1980
> 
> $ tail -f error.log
> 2021/02/22 15:41:42 [warn] 23035#23035: *66190 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (1/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> 2021/02/22 15:41:48 [warn] 23035#23035: *66445 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> 
> 2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1980)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> 2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1981)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> ```
> 
> 3、When the port of `1985` recovered health and view error.log
> 
> When an unhealthy node is restored to a healthy node, it will be automatically marked as healthy.
> 
> ```
> 2021/02/22 15:57:32 [warn] 23035#23035: *107236 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> ```

What are the requirements for this health check method?  when my node is unhealthy , the auto healthy check method work。and response http header status =200 。but still not marked as healthy

**Comment by tokers** [comment] 2021-02-25 10:27
> > Hi, @yocaning
> > You need to pay attention to your configuration. The `http_path` of the active health check should be consistent with the uri that provides the service. Secondly, the value of `"timeout":1` is recommended to be set larger.
> > This is an example, you can refer to it
> > 1、Add a route and enable health check
> > The 1981 and 1982 ports are healthy, but the 1985 port is unhealthy.
> > ```shell
> > curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> > {
> >     "id":"1",
> >     "update_time":1613734165,
> >     "upstream":{
> >         "checks":{
> >             "active":{
> >                 "healthy":{
> >                     "interval":3,
> >                     "successes":2
> >                 },
> >                 "unhealthy":{
> >                     "interval":10,
> >                     "http_failures":2
> >                 },
> >                 "timeout":10,
> >                 "http_path":"/hello",
> >                 "type":"http",
> >                 "req_headers":[
> >                     "Content-Seq:3"
> >                 ]
> >             },
> >             "passive":{
> >                 "timeout":5,
> >                 "healthy":{
> >                     "http_statuses":[
> >                         200,
> >                         201
> >                     ],
> >                     "successes":3
> >                 },
> >                 "type":"http",
> >                 "unhealthy":{
> >                     "http_statuses":[
> >                         500,
> >                         504
> >                     ],
> >                     "timeouts":3,
> >                     "tcp_failures":1,
> >                     "http_failures":1
> >                 }
> >             }
> >         },
> >         "nodes":{
> >             "127.0.0.1:1980":1,
> >             "127.0.0.1:1981":1,
> >             "127.0.0.1:1985":1
> >         },
> >         "timeout":{
> >             "connect":3,
> >             "read":3,
> >             "send":3
> >         },
> >         "pass_host":"pass",
> >         "hash_on":"vars",
> >         "type":"roundrobin"
> >     },
> >     "methods":[
> >         "PUT",
> >         "GET"
> >     ],
> >     "status":1,
> >     "create_time":1613722689,
> >     "priority":0,
> >     "uri":"/hello"
> > }'
> > ```
> > 
> > 
> > 2、Access request and view error.log
> > ```
> > $ curl http://127.0.0.1:9080/hello
> > hello 1980
> > 
> > $ tail -f error.log
> > 2021/02/22 15:41:42 [warn] 23035#23035: *66190 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (1/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> > 2021/02/22 15:41:48 [warn] 23035#23035: *66445 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) unhealthy TCP increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> > 
> > 2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1980)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> > 2021/02/22 15:42:56 [warn] 23036#23036: *69367 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (1/2) for '(127.0.0.1:1981)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> > ```
> > 
> > 
> > 3、When the port of `1985` recovered health and view error.log
> > When an unhealthy node is restored to a healthy node, it will be automatically marked as healthy.
> > ```
> > 2021/02/22 15:57:32 [warn] 23035#23035: *107236 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/apisix/routes/1) healthy SUCCESS increment (2/2) for '(127.0.0.1:1985)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
> > ```
> 
> What are the requirements for this health check method? when my node is unhealthy , the auto healthy check method work。and response http header status =200 。but still not marked as healthy

The active health checker needs more times try to judge whether a node is healthy or unhealthy, not just one time. 
See https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L134. You may tweak these args to see the change.

**Closed** 2021-06-18 06:54 UTC
