### ISSUE TITLE
help request: Configure ssl certs for upstream health check

### ISSUE THREAD

**Issue by anandasastry** [apache/apisix#9993] opened 2023-08-09 00:04 UTC
### Description

I have 2 upstream servers for which I am trying like to setup a health check using https protocol. I get the below error

SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

How to configure the certificates for upstream health check?

### Environment

- APISIX version (run `apisix version`): 3.4.1
- Operating system (run `uname -a`): MacOS
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: 3.4.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 3.9.2

**Comment by shreemaan-abhishek** [comment] 2023-08-09 04:42
Can you share your approach? I see that the documentation is missing.

**Comment by shreemaan-abhishek** [comment] 2023-08-11 06:08
> SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

Is this the only error you get? Is there anything else in the error.log?

I tried setting up https healthcheck and it worked fine for me:
```curl -vvv http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "upstream": {
         "nodes": {
            "https://www.google.com": 1
        },
        "type": "roundrobin",
        "retries": 2,
        "checks": {
            "active": {
                "timeout": 5,
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                },
                "type": "https"
            }
        }
    }
}'
```

Can you try disabling mTLS and see if the health check works? Also, many users have reported compatibility issues between the dashboard and apisix. Try loading the SSL resources using the admin api: https://apisix.apache.org/docs/apisix/admin-api/#ssl

**Comment by anandasastry** [comment] 2023-08-15 01:28
The health check has to be done on the same port used for API routing. So, mTLS cannot be disabled. Is there a way to customise the health check to support mTLS?

**Comment by shreemaan-abhishek** [comment] 2023-08-15 04:17
> Is there a way to customise the health check to support mTLS?

I'm not saying that this isn't supported.

Did you try loading the SSL resources using the admin api?
Did you try disabling mTLS and _just to see_ if the health check works without mTLS?

Please share your route/upstream configurations.

**Comment by anandasastry** [comment] 2023-08-15 16:52
I tried to remove the SSL certs and load again. But still not working. 

The complete error is 

SSL_do_handshake() failed (SSL: error:14094412:SSL routines:ssl_read_bytes:sslv3 alert bad certificate: SSL alert number 42), context ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9443
[lua] healthcheck.lua:958: run_single_check(): [healthcheck] [upstream#/apisix/routes/472419835670693804] failed SSL handshake with ' (_**upstream ip:port**_)' using server name [sni] 'nil': handshake failed, context ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9443

Since there is no option to specify client cert or key for the mTLS during health check, can you please let me know how APISIX will determine the client certificate to be sent to upstream 

I tried enabling the health check on a different upstream port using Basic Auth and it works fine.

**Comment by shreemaan-abhishek** [comment] 2023-08-16 10:43
**Please share your route/upstream configurations.**

Also, please provide detailed reproduction steps

**Comment by Sn0rt** [comment] 2023-08-21 03:38
can we add test case for https health check ?

**Comment by anandasastry** [comment] 2023-08-21 23:04
Am able to get the mTLS working for healthcheck. But, I have a question. Is there a way to retrieve the upstream hostname configured in the route, in healthcheck.lua or is it possible to do a dns lookup of the ipaddress and retrieve the upstream hostname?

**Comment by shreemaan-abhishek** [comment] 2023-08-22 05:48
@anandasastry, what is your use case?

**Comment by anandasastry** [comment] 2023-08-29 16:17
@shreemaan-abhishek I would like to determine client cert and client key to be used for the upstream mTLS during health check, based on the hostname. But I am only able to retrieve ip address of the upstream node.

**Comment by shreemaan-abhishek** [comment] 2023-09-05 04:20
> I would like to determine client cert and client key to be used for the upstream mTLS during health check, based on the hostname

I am not quite sure if that can be done. Could you please share your upstream/route configurations?

**Comment by shreemaan-abhishek** [comment] 2023-11-22 06:38
Closing since the main issue has been resolved: https://github.com/apache/apisix/issues/9993#issuecomment-1687176330

**Comment by monkeyDluffy6017** [comment] 2023-11-22 06:39
@anandasastry you can create a new issue for the new question, thanks!

**Closed by shreemaan-abhishek** 2023-11-22 06:38 UTC
Labels: bug, wait for update
