### ISSUE TITLE
ci: the ci gets this error when running

### ISSUE THREAD

**Issue by monkeyDluffy6017** [apache/apisix#9540] opened 2023-05-24 09:20 UTC
### Current Behavior

The ci frequently gets this error when running

### Expected Behavior

No error when ci is running

### Error Logs

https://github.com/apache/apisix/actions/runs/5066397232/jobs/9096148444?pr=9534
https://github.com/apache/apisix/actions/runs/5063566059/jobs/9090313885

![image](https://github.com/apache/apisix/assets/9354193/b606601e-2db5-4b5a-bcc7-93432ba3cd54)

### Steps to Reproduce

The error doesn't always occur,  we should analyze the log and code

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment] 2023-05-24 09:33
please assign this to me.

**Comment by shreemaan-abhishek** [comment] 2023-05-25 04:31
@monkeyDluffy6017, I checked those errors and I can confirm that all errors are normal and expected. And they do not effect the CI at all.

**Comment by Revolyssup** [comment] 2023-05-25 05:05
> @monkeyDluffy6017, I checked those errors and I can confirm that all errors are normal and expected. And they do not effect the CI at all.

But they are failing the CI so shouldn't they be addressed? Some of these were failing in my PRs as well https://github.com/apache/apisix/actions/runs/5065375877/jobs/9093970631.

**Comment by Revolyssup** [comment] 2023-05-25 05:18
@monkeyDluffy6017 @shreemaan-abhishek 
Here[1] we give the config to listen on 12345 and here[2] we try to connect to it but it says connection refused. Can it be the case that we need to add some wait time of few seconds in between to make sure the socket is available.
1. https://github.com/apache/apisix/blob/a992cd80a8a7dd2fd258b82d414ea34c371e5b12/t/deployment/conf_server.t#L258
2. https://github.com/apache/apisix/blob/a992cd80a8a7dd2fd258b82d414ea34c371e5b12/t/deployment/conf_server.t#L275

**Comment by monkeyDluffy6017** [comment] 2023-05-25 06:02
This problem has been bothering us for a long time, it will fail the ci, I would be very grateful if this could be resolved

**Comment by shreemaan-abhishek** [comment] 2023-05-25 06:04
conf_server.t is a flaky test

https://github.com/apache/apisix/actions/runs/5064563181/jobs/9092277069#step:19:286
https://github.com/apache/apisix/actions/runs/5054522326/jobs/9069591264#step:19:290

**Comment by Revolyssup** [comment] 2023-05-25 06:07
> conf_server.t is a flaky test
> 
> https://github.com/apache/apisix/actions/runs/5064563181/jobs/9092277069#step:19:286 https://github.com/apache/apisix/actions/runs/5054522326/jobs/9069591264#step:19:290
> 
> Lemme check if waiting for sometime works or not.

Nope I tried adding wait, it didn't work but then after some time it worked even without wait. You're right, its flaky. Im trying to find, why

**Comment by monkeyDluffy6017** [comment] 2023-05-27 15:41
Do we have any progress?

**Comment by shreemaan-abhishek** [comment] 2023-05-27 16:10
@monkeyDluffy6017 no progress so far. 

I wanted to ssh into the github action container to investigate those errors. I ran the ci on my fork repo 4 times and the tests passed every time. So this really looks like a flaky test that passes every time locally but occasionally fails on the ci. Would you happen to have any hint/clue for me so that I can make any progress or start a fresh investigation from a new point of view?

<img width="361" alt="image" src="https://github.com/apache/apisix/assets/61597896/7946c456-2dfa-4750-9f6d-cc89e63ddec6">

**Comment by lingsamuel** [comment] 2023-06-20 08:13
Any progress? @shreemaan-abhishek

**Comment by shreemaan-abhishek** [comment] 2023-06-21 04:19
> Any progress? @shreemaan-abhishek

Looks like a flaky test. I don't see anything that can be done to fix this.

**Comment by Revolyssup** [comment] 2023-09-18 10:09
@shreemaan-abhishek Is this test still failing?

**Comment by AlinsRan** [comment] 2023-09-18 10:58
https://github.com/apache/apisix/pull/10012

The PR #10012 `conf_server`  has been removed and this test case is no longer needed.

We can close this issue.

**Closed** 2023-09-18 11:12 UTC
Labels: bug
