### ISSUE TITLE
help request: apisix restart fail

### ISSUE THREAD

**Issue by lisea2017** [apache/apisix#10495] opened 2023-11-15 09:00 UTC
### Description

After the apisix process is running, when the command 'apisix restart' is executed, the apisix process disappears without any error messages. What could be the issue?

### Environment

- APISIX version (run `apisix version`): 3.6.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant:3.0.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):3.8.0

**Comment by moonming** [comment] 2023-11-15 09:41
Without error logs and core dumps, there is no way to tell

**Comment by lisea2017** [comment] 2023-11-23 02:19
How can I find error logs? The error.log only shows [notice] 15846#15846: signal process started, and after restarting, it indicates 'configuration test is successful.' APISIX is running... Where else can I check?

**Comment by luoluoyuyu** [comment] 2023-12-04 06:05
Hi @lisea2017 
I think you've rebooted successfully and it looks like this.
![image](https://github.com/apache/apisix/assets/82068138/928759c0-9da9-4410-8311-451f19d109ea)

**Comment by lisea2017** [comment] 2023-12-05 09:00
The display is the same as yours, but when using the command `ps -ef | grep apisix`, it shows that the process no longer exists.

**Comment by monkeyDluffy6017** [comment] 2023-12-12 10:09
@lisea2017 have you solved your problem?

**Comment by lisea2017** [comment] 2023-12-13 03:28
No, it has always been the case. I can only use reload as a replacement now.

**Comment by monkeyDluffy6017** [comment] 2023-12-13 04:04
@luoluoyuyu could you help to check this?

**Comment by luoluoyuyu** [comment] 2023-12-13 05:47
Hi @lisea2017 
You are right, I also had this problem, when I executed `apisix restart` and then executed `ps -ef` command no apisix process was found. When I execute `apisix restart` again to reboot successfully.

**Comment by hanqingwu** [comment] 2023-12-22 08:39
i have got a root cause,  so i can submit a PR . 
when apisix is running and after kill,  it return to exit 

--- a/apisix/cli/ops.lua
+++ b/apisix/cli/ops.lua
@@ -805,8 +805,8 @@ local function start(env, ...)
 
         local ok, err, err_no = signal.kill(pid, signone)
         if ok then
-            print("APISIX is running...")
-            return
+            print("APISIX is running... and now kill ...")
+        --    return
         -- no such process
         elseif err_no ~= errno.ESRCH then
             print(err)

**Comment by Vacant2333** [comment] 2024-01-08 10:24
@lisea2017 hello, this issue looks was resolved, can we close it now

**Closed** 2024-01-09 01:29 UTC
Labels: bug, help wanted
