### ISSUE TITLE
bug: `group conf mismatched` when using `$consumer_group_id` as the rate limiting group on `limit-count`

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10100] opened 2023-08-28 13:49 UTC
### Description

Create two consumer groups of different IDs with different rate limiting policies, where `$consumer_group_id` was configured as the rate limiting group such that the same group share the same rate limiting counter:

![image](https://github.com/apache/apisix/assets/39619599/4a6e0bd2-a2d4-40e4-8323-7260bf013212)

Followed the [docs here](https://apisix.apache.org/docs/apisix/next/terminology/consumer-group/#example).

Not sure why I got the error message `group conf mismatched` as I was NOT applying different `limit-count` configurations on the same consumer group, as mentioned [in the `limit-count` doc](https://apisix.apache.org/docs/apisix/plugins/limit-count/).

![image](https://github.com/apache/apisix/assets/39619599/a52f3853-0f2d-4cf2-947d-424ad9e60a6c)

### Environment

- APISIX version (run `apisix version`): 3.4.0

**Comment by kayx23** [comment] 2023-08-28 13:55
@navendu-pottekkat I see [this blog](https://apisix.apache.org/blog/2023/08/14/rate-limit/#grouping-consumers) wrote the consumer group ID twice, in both the `{id}` and the `group` configuration. I thought `$consumer_group_id` was used to avoid exactly the manual input of the same info twice to avoid update anomalies. 

Did you stumble across the same issue as this one by chance?

**Comment by navendu-pottekkat** [comment] 2023-08-28 16:32
> Did you stumble across the same issue as this one by chance?

No, I did not. What happens when you mention the consumer group explicitly in both places? Do you stumble across the same error?

**Comment by Revolyssup** [comment] 2023-08-29 05:11
@kayx23 What do you get in your error logs when this happens?
grep for something like `previous limit-conn group `

**Comment by Revolyssup** [comment] 2023-08-29 05:27
@kayx23 Actually you're right. There is a caching issue here - https://github.com/apache/apisix/blob/704645f6114ce6f2a4fe79857a8049e693f3878c/apisix/plugins/limit-count/init.lua#L185

Even if the consumer group is deleted, this cache will still return the previously detected conf for that consumer group.

**Comment by kayx23** [comment] 2023-08-29 05:28
@Revolyssup Re-run something similar and here's the log:

```
2023/08/29 05:24:44 [error] 128#128: *2272936 [lua] init.lua:189: check_schema(): previous limit-conn group $consumer_group_id conf: {"time_window":30,"key_type":"var","count":2,"show_limit_quota_header":true,"policy":"local","rejected_code":503,"allow_degradation":false,"key":"remote_addr","group":"$consumer_group_id"}, client: 172.21.0.1, server: , request: "PUT /apisix/admin/consumer_groups HTTP/1.1", host: "127.0.0.1:9180"
2023/08/29 05:24:44 [error] 128#128: *2272936 [lua] init.lua:191: check_schema(): current limit-conn group $consumer_group_id conf: {"time_window":30,"key_type":"var","rejected_code":429,"show_limit_quota_header":true,"policy":"local","key":"remote_addr","allow_degradation":false,"count":20,"group":"$consumer_group_id"}, client: 172.21.0.1, server: , request: "PUT /apisix/admin/consumer_groups HTTP/1.1", host: "127.0.0.1:9180"
172.21.0.1 - - [29/Aug/2023:05:24:44 +0000] 127.0.0.1:9180 "PUT /apisix/admin/consumer_groups HTTP/1.1" 400 110 0.000 "-" "curl/7.74.0" - - - "http://127.0.0.1:9180"
```

> check_schema(): previous limit-conn group $consumer_group_id conf...

I feel like `$consumer_group_id` might have been interpreted as a string literal here?

**Comment by Revolyssup** [comment] 2023-08-29 05:32
I can repro the Problem:
Limit count configuration on a consumer group is immutable i.e. you can't change it. But if you delete the consumer group then the cache should be cleared which doesn't happen. So APISIX tries to enforce immutability of plugin configuration on a consumer group that no longer exists. I will create a fix for this. 


![Screenshot from 2023-08-29 11-00-00](https://github.com/apache/apisix/assets/43276904/9f25558a-3bf9-4137-97e5-bf330e9eeb10)

**Comment by Revolyssup** [comment] 2023-08-29 05:33
@kayx23 In the original issue decription also I think you might at some point in time for the same apisix instance had a different plugin configuration for `premium_plan` consumer group which was deleted later on. But the error came due to caching issue.

**Comment by kayx23** [comment] 2023-08-29 05:37
@Revolyssup I actually didn't. I started new instances of APISIX and etcd in docker (because i suspected there was a caching related issue) and was still able to recreate the issue with just the following:

```shell
curl "http://127.0.0.1:9180/apisix/admin/consumer_groups" -X PUT -d '
{
  "id": "basic_plan",
  "plugins": {
    "limit-count": {
      "count": 2,
      "time_window": 30,
      "group": "$consumer_group_id"
    }
  }
}'
```

```shell
curl "http://127.0.0.1:9180/apisix/admin/consumer_groups" -X PUT -d '
{
  "id": "premium_plan",
  "plugins": {
    "limit-count": {
      "count": 20,
      "time_window": 30,
      "group": "$consumer_group_id"
    }
  }
}'
```

**Comment by Revolyssup** [comment] 2023-08-29 05:49
> 

Yeah this is because as you had stated earlier - $consumer_group_id is not interpreted as an ngx variable but rather as a string literal so the original issue is a non-issue. Though the fact the deleting the consumer group doesn't clear the cache is still an issue.

**Comment by Revolyssup** [comment] 2023-08-29 05:52
@kayx23 I think we can close this issue and I can open another one to fix the issue where cache is maintained even after consumer group is deleted.

**Comment by kayx23** [comment] 2023-08-29 05:53
> $consumer_group_id is not interpreted as an ngx variable but rather as a string literal so the original issue is a non-issue. 

But it should be evaluated as a built-in variable.

**Comment by Revolyssup** [comment] 2023-08-29 06:01
> t

Hmm, as far as I can see, this evaluation doesn't occur during config validation https://github.com/apache/apisix/blob/704645f6114ce6f2a4fe79857a8049e693f3878c/apisix/plugins/limit-count/init.lua#L159

**Comment by kayx23** [comment] 2023-08-29 06:26
Confirmed by @kingluo that that `group` field takes only a constant value and is not intended to eval a built-in variable.

**Comment by Revolyssup** [comment] 2023-08-30 06:05
Confirmed by @kingluo that that group field takes only a constant value and is not intended to eval a built-in variable.

**Closed by Revolyssup** 2023-08-30 06:05 UTC
Labels: bug
