### ISSUE TITLE
bug: Using proxy-rewrite to overwrite the request header x-forwarded-proto failed

### ISSUE THREAD

**Issue by gaobo0202** [apache/apisix#5858] opened 2021-12-20 03:43 UTC
### Issue description

Our upstream service relies on the parameter of x-forwarded-proto and uses the proxy rewrite plug-in to rewrite the parameter. The upstream service does not get the correct rewritten value
1. When APISIX configures the route, use proxy rewrite to rewrite the x-forwarded-proto parameter to http
2. After calling the domain name, it is found that the x-forwarded-proto obtained upstream is still HTTPS
After reading the code and the previous issue about the parameter rewriting, it is found that the proxy rewrite plug-in modification of the parameter will not take effect.
I modified the code of APISIX myself to make the proxy rewrite configuration x-forwarded-proto effective. Is this another good repair method?

![image](https://user-images.githubusercontent.com/14210651/146708511-0e9360a3-2956-40fb-aa97-941d8a85436b.png)
![image](https://user-images.githubusercontent.com/14210651/146708527-c78f54ea-52a8-4089-8d30-b20514995f34.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

Use proxy-rewrite to overwrite x-forwarded-proto

### Actual result

Override does not take effect

### Error log

no error log

### Expected result

No response

**Comment by tzssangglass** [comment] 2021-12-20 10:12
see: https://github.com/apache/apisix/issues/5080#issuecomment-921499970

**Comment by tzssangglass** [comment] 2021-12-20 10:15
it looks like there are three to four similar feedbacks now, maybe we should make proxy-rewrite support this.

**Comment by gaobo0202** [comment] 2021-12-21 01:07
> it looks like there are three to four similar feedbacks now, maybe we should make proxy-rewrite support this.

OK, can I modify the code like this? We plan to use it in the production environment

**Comment by tzssangglass** [comment] 2021-12-21 01:09
> > it looks like there are three to four similar feedbacks now, maybe we should make proxy-rewrite support this.
> 
> OK, can I modify the code like this? We plan to use it in the production environment

It is recommended to use the plugin rather than modifying the source code.

**Comment by tzssangglass** [comment] 2021-12-21 01:09
> it looks like there are three to four similar feedbacks now, maybe we should make proxy-rewrite support this.

cc @spacewander

**Comment by gaobo0202** [comment] 2021-12-21 02:00
> > > it looks like there are three to four similar feedbacks now, maybe we should make proxy-rewrite support this.
> > 
> > 
> > OK, can I modify the code like this? We plan to use it in the production environment
> 
> It is recommended to use the plugin rather than modifying the source code.

What I modified is the plug-in code. Can I integrate it into the master？

**Comment by tzssangglass** [comment] 2021-12-21 03:46
did you implement this in proxy-rewrite? If so, feel free to submit a PR.

**Comment by gaobo0202** [comment] 2021-12-22 02:30
> 

ok

**Comment by spacewander** [comment] 2021-12-22 06:09
> see: [#5080 (comment)](https://github.com/apache/apisix/issues/5080#issuecomment-921499970)

These are different things. The `X-Forwarded-Proto` should already be supported since https://github.com/apache/apisix/pull/4260.

@gaobo0202 
Could you provide detailed reproduce steps?

**Comment by gaobo0202** [comment] 2021-12-22 07:50
1、use proxy-rewrite to rewrite x_forwarded_proto to HTTP and enable HTTPS in router
2、access domain (add x_forwarded_proto request header HTTPS or not)
3、The upstream service gets x_forwarded_proto value
result
The value of x_forwarded_proto obtained by the upstream service is HTTPS

**Comment by gaobo0202** [comment] 2021-12-22 07:50
> > see: [#5080 (comment)](https://github.com/apache/apisix/issues/5080#issuecomment-921499970)
> 
> These are different things. The `X-Forwarded-Proto` should already be supported since #4260.
> 
> @gaobo0202 Could you provide detailed reproduce steps?

1、use proxy-rewrite to rewrite x_forwarded_proto to HTTP and enable HTTPS in router
2、access domain (add x_forwarded_proto request header HTTPS or not)
3、The upstream service gets x_forwarded_proto value
result
The value of x_forwarded_proto obtained by the upstream service is HTTPS

**Comment by gaobo0202** [comment] 2021-12-22 07:58
> 

In addition, I found that this test case was not passed, please help to confirm
![image](https://user-images.githubusercontent.com/14210651/147056735-4046e8ab-fcc3-4b72-b7f2-416021960b13.png)

**Comment by gaobo0202** [comment] 2021-12-22 08:00
> > > see: [#5080 (comment)](https://github.com/apache/apisix/issues/5080#issuecomment-921499970)
> > 
> > 
> > These are different things. The `X-Forwarded-Proto` should already be supported since #4260.
> > @gaobo0202 Could you provide detailed reproduce steps?
> 
> 1、use proxy-rewrite to rewrite x_forwarded_proto to HTTP and enable HTTPS in router 2、access domain (add x_forwarded_proto request header HTTPS or not) 3、The upstream service gets x_forwarded_proto value result The value of x_forwarded_proto obtained by the upstream service is HTTPS

In addition, I found that this test case was not passed, please help to confirm （proxy-rewrite2.t）
![image](https://user-images.githubusercontent.com/14210651/147056908-ef301c29-fa2f-46a4-bc08-6c12268d619a.png)

**Comment by spacewander** [comment] 2021-12-22 13:01
The test can pass in CI & my machine.
I also set up an environment and test for it, the proxy-rewrite plugin can change X-Forwarded-Proto from HTTPS to HTTP.

**Comment by leslie-tsang** [comment] 2021-12-24 03:20
@juzhiyuan Plz, assign to me.

**Closed** 2021-12-24 08:02 UTC
Labels: discuss, wait for reproduce
