### ISSUE TITLE
支持API编排吗

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5076] opened 2021-09-16 07:54 UTC
### Issue description

支持API编排吗？或者有什么插件实现这个功能吗

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

支持API编排吗？或者有什么插件实现这个功能吗

### Actual result

支持API编排吗？或者有什么插件实现这个功能吗

### Error log

支持API编排吗？或者有什么插件实现这个功能吗

**Comment by spacewander** [comment] 2021-09-16 08:15
Duplicate of https://github.com/apache/apisix/issues/4761?

**Comment by tzssangglass** [comment] 2021-09-16 14:14
not support yet, do you have any ideas for this feature?

**Comment by spacewander** [comment] 2021-09-17 01:44
Let's discuss it in one issue: https://github.com/apache/apisix/issues/4761

**Closed by spacewander** 2021-09-17 01:44 UTC
Labels: duplicate
