### ISSUE TITLE
bug: Negative value option reports an error.

### ISSUE THREAD

**Issue by freemankevin** [apache/apisix#9099] opened 2023-03-17 03:42 UTC
### Current Behavior

Since you cannot set a negative value, why do you have such a scroll wheel option? ? ? Ha ha
![image](https://user-images.githubusercontent.com/71524776/225807016-b2ef0177-5386-4a28-a466-5dee0b0a5ba6.png)

### Steps to Reproduce

1

### Environment

`docker-compose`   deploy the latest version.

**Comment by Neilblaze** [comment] 2023-03-19 09:45
@freemankevin Duplicate of [#2775](https://github.com/apache/apisix-dashboard/issues/2775)
Related to [`apisix-dashboard`](https://github.com/apache/apisix-dashboard). A [PR](https://github.com/apache/apisix-dashboard/pull/2777) has been raised for resolution.

**Closed** 2023-03-20 01:17 UTC
