### ISSUE TITLE
The filter in plugin configuration _meta does not work in 2.15.0

### ISSUE THREAD

**Issue by yuqiquan** [apache/apisix#8003] opened 2022-09-28 03:47 UTC
### Description

首先有两个插件
大致流程是

客户端请求经过第一个插件，会在请求头中添加属性
![image](https://user-images.githubusercontent.com/44921350/192682585-f231a751-1f03-4c5d-8ed8-cfc87ec7b42f.png)

然后第二个插件会进行这样的配置
![image](https://user-images.githubusercontent.com/44921350/192682652-797a40a3-aba2-45f5-9f27-d3ee75faad47.png)

按理说不等于的时候才会执行第二个插件，但是经过我的测试不管是等不等于，插件都会执行

所以我认为可能是filter属性没起效果，获取不到请求头里的属性值

但是我在第二个插件的access阶段，获取请求头属性值是成功的

### Environment

- APISIX version 2.15.0

**Comment by spacewander** [comment] 2022-09-28 06:26
Duplicate of #7852

TL;DR: currently the evaluation of the filter happens when we decide which plugins should be run in the matched route. So any change after that (for example, "经过第一个插件，会在请求头中添加属性") will not affect the evaluated filter result.

**Closed by spacewander** 2022-09-28 06:26 UTC

**Comment by yuqiquan** [comment] 2022-09-28 06:47
I get it. Thanks
