### ISSUE TITLE
Failed installing dependency

### ISSUE THREAD

**Issue by phperEric** [apache/apisix#3898] opened 2021-03-24 02:25 UTC
make deps 
```
Installing https://luarocks.org/luasec-0.9-1.src.rock

Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [deps] 错误 1

```

```
# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

```

**Comment by spacewander** [comment] 2021-03-24 02:30
Duplicate of #3886

**Closed by spacewander** 2021-03-24 02:30 UTC
