### ISSUE TITLE
docs: upgrade/migration manual is missing

### ISSUE THREAD

**Issue by hegw** [apache/apisix#5141] opened 2021-09-27 01:07 UTC
### Improved or typo fixed.

there's no document content that tell us how to upgrade/migrate apisix to a newer release，it's a problem to users.

### Solution

hope there's a chapter for upgrade/migration in the document of Apisix.

**Comment by spacewander** [comment] 2021-09-27 02:08
Duplicate of #4310

**Closed by spacewander** 2021-09-27 02:08 UTC
Labels: doc
