### ISSUE TITLE
chore: when etcd is not started, need to print a more friendly warning message

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3190] opened 2021-01-05 03:16 UTC
`got malformed version message: "" from etcd` is not easy to understand.

```shell
$ make init
./bin/apisix init
./bin/apisix init_etcd
got malformed version message: "" from etcd
make: *** [Makefile:80: init] Error 1

**Comment by spacewander** [comment] 2021-01-05 03:21
Duplicate of #2718

**Closed by spacewander** 2021-01-05 03:21 UTC
Labels: good first issue

**Comment by membphis** [comment] 2021-01-05 03:54
nice, thx
