### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by yuhaizr** [apache/apisix#4618] opened 2021-07-17 01:22 UTC
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.7
* OS (cmd: `uname -a`):2.6.32-754.24.3.el6.x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.0.4

 执行完 make deps 之后 执行 make init 报以下错误，麻烦帮忙看看怎么解决？
./bin/apisix init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so':
        /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list
stack traceback:
        [C]: at 0x00452d70
        [C]: in function 'require'
        /usr/local/apisix-2.7/deps/share/lua/5.1/ssl.lua:8: in main chunk
        [C]: in function 'require'
        /usr/local/apisix-2.7/deps/share/lua/5.1/ssl/https.lua:10: in main chunk
        [C]: in function 'require'
        ./apisix/cli/etcd.lua:24: in main chunk
        [C]: in function 'require'
        ./apisix/cli/ops.lua:18: in main chunk
        [C]: in function 'require'
        ./apisix/cli/apisix.lua:32: in main chunk
        [C]: at 0x00404c80

**Comment by spacewander** [comment] 2021-07-17 10:29
Duplicate of #4594

**Closed by spacewander** 2021-07-17 10:29 UTC
