### ISSUE TITLE
help request:   I can't enter dashboard but it works

### ISSUE THREAD

**Issue by Meguais** [apache/apisix#9678] opened 2023-06-16 04:50 UTC
### Description

[https://prnt.sc/PYZr6346w5rV](https://prnt.sc/PYZr6346w5rV)

apisix and apisix dashboard run i cant browse http://127.0.0.1:9000

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Meguais** [comment] 2023-06-16 04:53
i get {"Code":20002,"Message":"IP address not allowed","Data":null,"SourceSrv":""} how can i access

**Comment by Revolyssup** [comment] 2023-06-16 05:55
Can you share the content of the file stored in `/usr/local/apisix/dashboard/conf/conf.yaml`

**Comment by Meguais** [comment] 2023-06-16 20:46
thank you

**Comment by lingsamuel** [comment] 2023-06-19 03:09
I guess the issue is solved, so I am closing this one

**Closed by lingsamuel** 2023-06-19 03:09 UTC
