### ISSUE TITLE
request help: make uninstall failed on Mac

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#6226] opened 2022-01-28 06:31 UTC
### Issue description

After `make install`  partial successful steps, no easy way to uninstall, include main dir `/usr/local/apisix` and all the lua libs through `make deps`.

Hopefully support `make uninstall` and `make undeps`

```bash
➜  apisix git:(master) make uninstall
make: *** No rule to make target `uninstall'.  Stop.
➜  apisix git:(master) make undeps
make: *** No rule to make target `undeps'.  Stop.
```

### Environment

- OS (cmd: `uname -a`): Darwin Kwanhur-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

**Comment by spacewander** [comment] 2022-01-28 07:12
Duplicate of https://github.com/apache/apisix/issues/5225

**Closed by spacewander** 2022-01-28 07:12 UTC
