### ISSUE TITLE
request help: How to do that make apisix  not strictly abide by the SNI protocol

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4695] opened 2021-07-29 02:57 UTC
### Environment

* apisix version (cmd: `apisix version`): 2.5

When the HTTPS passes Alibaba cloud's WAF, the SNI protocol is lost and apisix directly reports an error of sni

**Comment by spacewander** [comment] 2021-07-29 03:12
This is a known bug of aliyun's WAF. It doesn't proxy the SNI even in 2021.

**Comment by StretchV** [comment] 2021-07-29 03:15
Can apisix add a switch to control whether apixis is strictly SNI

**Comment by spacewander** [comment] 2021-07-29 03:16
My suggestion is to use another cloud vendor which WAF works in a modern way. It's **technically impossible** to load certificates dynamically without knowing the SNI, unless you can deploy your own TLS handshake protocol.

**Comment by StretchV** [comment] 2021-07-29 03:19
There are many historical reasons why the exchange WAF cost is too high,What I mean is to return a default without getting SNI instead of directly returning it, like ingress

**Comment by spacewander** [comment] 2021-07-29 03:42
Duplicate of https://github.com/apache/apisix/issues/3147
See my suggestion in https://github.com/apache/apisix/issues/3147#issuecomment-752039772. The thing may change since it is written a half year ago.
If you submit a PR we can accept it.

**Closed by spacewander** 2021-07-29 03:42 UTC
Labels: can't fix by us

**Comment by eddycjy** [comment] 2021-07-29 03:44
> My suggestion is to use another cloud vendor which WAF works in a modern way. It's **technically impossible** to load certificates dynamically without knowing the SNI, unless you can deploy your own TLS handshake protocol.

AliCloud is the largest cloud vendor in China, and changing the WAF is no longer just a software issue, but an enterprise capital issue.

Are there other better ways, such as allowing users to configure their own default certificates, rather than just rejecting them and thus making them unavailable?

**Comment by spacewander** [comment] 2021-07-29 03:53
I already provide a suggestion about how to do that.

> 
> 
> Duplicate of #3147
> See my suggestion in [#3147 (comment)](https://github.com/apache/apisix/issues/3147#issuecomment-752039772). The thing may change since it is written a half year ago.
> If you submit a PR we can accept it.

**Comment by spacewander** [comment] 2021-07-29 04:09
Also, it is a piece of good news for Tencent cloud and Huawei cloud, and other cloud vendors.
If Aliyun WAF doesn't even support proxying SNI in 2021, why not take a look at other cloud vendors which probably do better?
