### ISSUE TITLE
chore: Supplement the schema in deployment 

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix#8804] opened 2023-02-07 06:52 UTC
### Description

Apache APISIX v3 adds a decoupled deployment mode. ref: https://apisix.apache.org/docs/apisix/deployment-modes/#decoupled

The current schema is not perfect. 

When the role is `control_plane`, it should contain the configuration of the `admin` field, which is consistent with traditional.

https://github.com/apache/apisix/blob/5984321c34d3cdc90573ebbecfd17ba9082fb3ba/apisix/cli/schema.lua#L375-L412

xref: https://github.com/apache/apisix-helm-chart/issues/459

**Comment by jiangfucheng** [comment] 2023-02-07 07:54
Hi, could assign it me, i want to try it.

**Comment by rukundob451** [comment] 2023-02-11 23:03
@tao12345666333 was the issue worked on?

**Comment by tokers** [comment] 2023-02-12 10:26
@jiangfucheng Did you start it? I can assign it to you.

**Comment by jiangfucheng** [comment] 2023-02-12 11:25
> @jiangfucheng Did you start it? I can assign it to you.

I was submit a pr https://github.com/apache/apisix/pull/8809, but still has some problem, could you guide me slove it? I can't reproduce it in my local machine.

**Closed** 2023-02-15 01:46 UTC
Labels: help wanted, good first issue
