### ISSUE TITLE
feat: Support to set the upstream host dynamically

### ISSUE THREAD

**Issue by zsmlinux** [apache/apisix#10981] opened 2024-02-29 06:33 UTC
### Description

Such as:
![image](https://github.com/apache/apisix/assets/10682145/a60060cc-f355-4693-b9d0-09bcec889de0)

* scheme support `ws` `wss`
* for this example, $1 $2 is ip，$3 is port, host is `$1:$3` , that host can be set dynamically

**Comment by shreemaan-abhishek** [comment] 2024-02-29 06:51
could you please elaborate more? Please add a screenshot in english so others can help as well.

**Comment by zsmlinux** [comment] 2024-02-29 06:52
> could you please elaborate more? Please add a screenshot in english so others can help as well.
Such as:
```
  "plugins": {
    "proxy-rewrite": {
      "host": "$1:$3",
      "regex_uri": [
        "^/(\\d+\\.\\d+\\.\\d+\\.\\d+)/(\\d+\\.\\d+\\.\\d+\\.\\d+)/(\\d+)/(.*)",
        "/$4"
      ],
      "scheme": "wss"
    }
  },
```

**Comment by zsmlinux** [comment] 2024-02-29 06:58
Host can be set dynamically based on the uri for pattern matching, that is a common usage in nginx.

**Comment by kayx23** [comment] 2024-02-29 07:39
Same interest in this issue https://github.com/apache/apisix/issues/9544

**Comment by theweakgod** [comment] 2024-03-01 02:14
So, u want something that dynamically forwards requests upstream based on the path, for example, if ur request path is "/172.17.0.1/127.0.0.1/9999/real_path", u want Apisix to be designed in a way that it can forward the request to "172.17.0.1:9999"? Did I understand correctly?

**Comment by theweakgod** [comment] 2024-03-01 02:25
If designed this way, wouldn't there be risks? For example, someone could potentially call the Apisix admin API by using path"/127.0.0.1/127.0.0.1/9180/apisix/admin/routers" like the default ADMIN_API_KEY, allowing them to operate routers to cause damage.

**Comment by zsmlinux** [comment] 2024-03-01 03:00
> So, u want something that dynamically forwards requests upstream based on the path, for example, if ur request path is "/172.17.0.1/127.0.0.1/9999/real_path", u want Apisix to be designed in a way that it can forward the request to "172.17.0.1:9999"? Did I understand correctly?

Exactly.

**Comment by zsmlinux** [comment] 2024-03-01 03:01
It doesn't matter, beacuse we can limit admin API access by IP addresses.

**Comment by theweakgod** [comment] 2024-03-01 03:05
> It doesn't matter, beacuse we can limit admin API access by IP addresses.

Yes, I know it's possible. However, other users that use this feature might also need to impose restrictions or perform additional operations. Perhaps we should consider other people's thoughts on this. I can handle this issue, but I remain skeptical.

**Comment by zsmlinux** [comment] 2024-03-01 03:46
Here is the same issue https://github.com/apache/apisix/issues/9544

**Comment by zsmlinux** [comment] 2024-03-11 11:51
> > It doesn't matter, beacuse we can limit admin API access by IP addresses.
> 
> Yes, I know it's possible. However, other users that use this feature might also need to impose restrictions or perform additional operations. Perhaps we should consider other people's thoughts on this. I can handle this issue, but I remain skeptical.

Has this feat been confirmed?

**Comment by theweakgod** [comment] 2024-03-12 02:26
> Has this feat been confirmed?

What do u think about this issue? @monkeyDluffy6017

**Comment by shreemaan-abhishek** [comment] 2024-03-15 14:09
closing as duplicate of #9544

**Closed by shreemaan-abhishek** 2024-03-15 14:09 UTC

**Comment by br41n10** [comment] 2024-04-12 05:00
@zsmlinux I have the same problem, and I write a custom plugin to achieve this.

checkout my gits: https://gist.github.com/br41n10/e2d378c7a04d4861b2f0cbf4d2476d71

This is a very basic implementation, modify on your needs.

**Comment by zsmlinux** [comment] 2024-04-19 02:39
> @zsmlinux I have the same problem, and I write a custom plugin to achieve this.
> 
> checkout my gits: https://gist.github.com/br41n10/e2d378c7a04d4861b2f0cbf4d2476d71
> 
> This is a very basic implementation, modify on your needs.

I had write a custom plugin too. 
https://github.com/zsmlinux/apisix-custom-plugins/blob/main/proxy-rewrite-dynamic-upstream.lua
