### ISSUE TITLE
help request: dubbo-proxy  can't find dubbo service

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/apisix#10648] opened 2023-12-13 14:41 UTC
### Description

Dear,
I fase issue  on the dubbo-proxy  plugin. Please help me.
1. I started docker apisix on mac(M2)
<img width="1709" alt="image" src="https://github.com/apache/apisix/assets/22955377/6dbc6a2a-2402-4a5a-a8ab-9c786edc23c9">
2. I created upstream as below
<img width="1507" alt="image" src="https://github.com/apache/apisix/assets/22955377/e1b09452-a466-4d52-8416-5b0b5496166d">
3. I created route as below
<img width="1709" alt="image" src="https://github.com/apache/apisix/assets/22955377/2de30a2a-928f-42c8-a6f3-21e2bf8f269d">

4.check dubbo interface,  status is correct
<img width="1098" alt="image" src="https://github.com/apache/apisix/assets/22955377/49c65c1a-8bc5-41cd-86c5-ec912b064d0e">

5. try to access dubbo interface via apisix, but got error response.
<img width="1369" alt="image" src="https://github.com/apache/apisix/assets/22955377/09f056e0-6a32-476a-aaf8-58def11992b7">

error log in apisix as below
<img width="1651" alt="image" src="https://github.com/apache/apisix/assets/22955377/74c88fda-0f8f-49b0-b13c-853f22b463be">
6. I tried  on linux centos,also has the same issue.

is anyone can help me? Thanks very much!

### Environment

APISIX 3.7.0
Operating system Mac(m2)
I used docker example  from docker-apisix， all docker container info as below
<img width="1681" alt="image" src="https://github.com/apache/apisix/assets/22955377/27bea345-1d44-40ff-896e-86417e147282">

**Comment by starsz** [comment] 2023-12-14 01:50
Hi @mayunSaicmotor  Maybe you can try to remove the "#  指定需要调用的 Dubbo 服务接口完整限定名 " in the request.

<img width="694" alt="image" src="https://github.com/apache/apisix/assets/25628854/49fc488b-dc4e-46bf-9f7a-291fc24f85d0">

**Comment by sheharyaar** [comment] 2023-12-18 12:10
I want to look into this, @monkeyDluffy6017 , please assign me this

**Comment by sheharyaar** [comment] 2023-12-18 12:13
> Hi @mayunSaicmotor Maybe you can try to remove the "# 指定需要调用的 Dubbo 服务接口完整限定名 " in the request.

@mayunSaicmotor any update on this after using @starsz suggestion ?

**Comment by sheharyaar** [comment] 2023-12-20 05:25
@mayunSaicmotor can you please explain to me the use of "registry_address", this field is not documented in our dubbo-proxy plugin page.

**Comment by mayunSaicmotor** [comment] 2023-12-20 12:20
<img width="1112" alt="image" src="https://github.com/apache/apisix/assets/22955377/608cc25e-da4a-432f-bd0b-fab98ef7845c">
<img width="1688" alt="image" src="https://github.com/apache/apisix/assets/22955377/64db954d-03f5-4712-93d9-f21b6ee0d760">

<img width="1692" alt="image" src="https://github.com/apache/apisix/assets/22955377/08992b85-6041-47d1-a1cc-3f8751f9bf8d">


> > Hi @mayunSaicmotor Maybe you can try to remove the "# 指定需要调用的 Dubbo 服务接口完整限定名 " in the request.
> 
> @mayunSaicmotor any update on this after using @starsz suggestion ?

still hve issues, please see my screenshots.

**Comment by sheharyaar** [comment] 2023-12-20 13:03
Thank you for the update, it would be really helpful for us to reproduce this faster, if you can give us the route and other apisix configs as text, and also the steps to reproduce using dubbo.

**Comment by sheharyaar** [comment] 2023-12-22 03:39
@mayunSaicmotor can you please give us the route and other apisix configs as text, and also the steps to reproduce using dubbo.

**Comment by mayunSaicmotor** [comment] 2023-12-26 15:27
curl http://120.78.12.91:9180/apisix/admin/upstreams/1   -X PUT -d '
{
    "nodes": {
        "172.18.0.67:7809": 1
    },
    "type": "roundrobin"
}'

curl http://120.78.12.91:9180/apisix/admin/routes/1   -X PUT -d '
{
    "uris": [
        "/hello"
    ],
    "plugins": {
        "dubbo-proxy": {
            "service_name": "com.rrht.common.service.sys.SysUserService",
            "service_version": "1.2.0",
            "method": "selectSysUserInfo"

        }
    },
    "upstream_id": 1
}'
curl http://120.78.12.91:9070/hello  -X POST --data '
{
    "service": "com.rrht.common.service.sys.SysUserService", # 指定需要调用的Dubbo服务接口完整限定名
    "method": "selectSysUserInfo",                                                         # 指定需要调用的Dubbo服务接口方法
    "parameters": [                                                            # 指定需要调用的Dubbo服务接口方法参数列表，每一个参数都要指定类型和值
        {               
            "type": "java.lang.Integer",
            "value": 1
        }
    ]
}'

**Comment by sheharyaar** [comment] 2023-12-26 17:45
Thanks, I will have a look and update to you after reproducing the issue.

**Comment by mayunSaicmotor** [comment] 2023-12-28 09:19
> Thanks, I will have a look and update to you after reproducing the issue.

Dear @sheharyaar ，Any update？

**Comment by mayunSaicmotor** [comment] 2024-01-01 05:32
Dear @sheharyaar ，Any update？Still waiting for response.

**Comment by sheharyaar** [comment] 2024-01-01 06:11
I am sorry @mayunSaicmotor , I am currently busy with another high priority bug, I will have to look at it later.

**Comment by mayunSaicmotor** [comment] 2024-01-08 08:41
Dear @sheharyaar ，Any update？Still waiting for response.

**Comment by sheharyaar** [comment] 2024-01-09 09:52
@mayunSaicmotor , I will be taking up this issue now and I will update you.

**Comment by sheharyaar** [comment] 2024-01-10 12:51
Hi @mayunSaicmotor , I was setting up the testing environment, since I don't have the exact service, can you please help me in the setting up of the service. Which sample at : https://github.com/apache/dubbo-samples is similar to your test case ?

**Comment by mayunSaicmotor** [comment] 2024-01-11 06:01
[parking-sys.zip](https://github.com/apache/apisix/files/13897904/parking-sys.zip)
@sheharyaar  you can  user this sample

**Comment by sheharyaar** [comment] 2024-01-11 14:37
I was able to reproduce the issue, I wil lbe debugging this further.

**Comment by sheharyaar** [comment] 2024-01-11 18:07
Hi @mayunSaicmotor , it seems there is issue with your application and service registration with nacos, this is the reason why nacos is unable to find the service. 

The APISIX error log  is correct. It says that the received response did not contain the value `0x33` used internally to decode the response (since dubbo sends a Map as response) : 
```
2024/01/11 23:02:40 [error] 25683#25683: *418547 dubbo: parse exception failed expected integer but actually met 0x33 near position 0x1
2024/01/11 23:02:40 [warn] 25683#25683: *418547 dubbo: response decode result failed 3�Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:com.rrht.sys.service.impl.SysUserService, selectSysUserInfo
java.lang.IllegalArgumentException: Service not found:com.rrht.sys.service.impl.SysUserService, selectSysUserInfo
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:134)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:80)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

I was able to setup your project, here is the nacos response from curl and the web interface. Their is a mismatch between the entries. :

```
$ curl -X GET 'http://127.0.0.1:8848/nacos/v2/ns/service/list'
{"code":0,"message":"success","data":{"count":1,"services":["parking-sys-test"]}}
```

![image](https://github.com/apache/apisix/assets/34273345/900c2227-d775-4da4-9c71-82250245e109)

I also tries using `groupName` parameter for the curl request, but still the response was the same.

This issue is not related to APISIX. If hope I was help you.
If you feel the issue can be closed, please close the issue. Have a great day!

**Comment by sheharyaar** [comment] 2024-01-11 18:46
I would suggest you to update the application from Java8 to a version that supports Dubbo version 3.x

**Comment by sheharyaar** [comment] 2024-01-11 21:08
Your service is detected by dubbo-api when running with nacos : 
![image](https://github.com/apache/apisix/assets/34273345/92290303-3e77-443d-b203-6fde1d8e96fd)

But the issue is that the method is not getting detected :
![image](https://github.com/apache/apisix/assets/34273345/bafff73a-cc26-4c93-b332-1ab06db74df7)

There seems some issue with the application code. The output from APISIX is valid because APISIX expects `0x33` at the response body when it tries to decode it. But since the service is not detected and dubbo returns an error, the decoding fails. 
```
2024-01-12 02:32:42.967 WARN  o.a.d.r.p.d.DecodeableRpcInvocation:83    [DUBBO] Decode rpc invocation failed: Service not found:com.rrht.sys.service.impl.SysUserService:3.2.0, selectSysUserInfo, dubbo version: 2.7.8, current host: 192.168.0.108
java.lang.IllegalArgumentException: Service not found:com.rrht.sys.service.impl.SysUserService:3.2.0, selectSysUserInfo
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:134)
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:80)
        at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
 ```

**Comment by mayunSaicmotor** [comment] 2024-01-12 09:55
Did you find the root cause? but I use java  to call the dubbo, it works fine.

**Comment by sheharyaar** [comment] 2024-01-12 09:59
I couldn't find the root cause in the code, please try to update the java and dubbo version for your project

**Comment by mayunSaicmotor** [comment] 2024-01-12 10:31
we used  the spring cloud alibaba, the dubbo version is 2.7.8, which version does the apisix support?  but we have  more than 100 projects use  the similar dubbo as cloud service,  it is very hard to upgrade.

**Comment by sheharyaar** [comment] 2024-01-12 11:04
Ok, I will try to find the root cause

**Comment by mayunSaicmotor** [comment] 2024-01-12 11:27
<img width="951" alt="image" src="https://github.com/apache/apisix/assets/22955377/eec7fea4-8c78-45ac-a78a-057d395caea0">
**I use the above  java code  to call the dubbo interface, it works fine as below.**
<img width="526" alt="image" src="https://github.com/apache/apisix/assets/22955377/ea6518a7-101a-4edc-8fd0-cfed01585612">

**Comment by sheharyaar** [comment] 2024-01-12 19:52
Hi @mayunSaicmotor , you are right, it can be invoked from another Java program, I will debug the dubbo-proxy plugin.

**Comment by sheharyaar** [comment] 2024-01-12 21:07
There is difference between the requests made by the Java program and Postman.

Request by Java Consumer Program (Successful) :
```
0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00   ..............E.
0010   01 9c 3e 9f 40 00 40 06 78 94 c0 a8 00 6c c0 a8   ..>.@.@.x....l..
0020   00 6c a4 38 1e 81 c8 57 27 57 4b a5 b2 5e 80 18   .l.8...W'WK..^..
0030   01 04 83 b7 00 00 01 01 08 0a 93 32 5f 60 93 32   ...........2_`.2
0040   5e 72 da bb c2 00 00 00 00 00 00 00 00 00 00 00   ^r..............
0050   01 58 05 32 2e 30 2e 32 30 28 63 6f 6d 2e 72 72   .X.2.0.20(com.rr
0060   68 74 2e 73 79 73 2e 73 65 72 76 69 63 65 2e 69   ht.sys.service.i
0070   6d 70 6c 2e 53 79 73 55 73 65 72 53 65 72 76 69   mpl.SysUserServi
0080   63 65 05 31 2e 32 2e 30 07 24 69 6e 76 6f 6b 65   ce.1.2.0.$invoke
0090   30 38 4c 6a 61 76 61 2f 6c 61 6e 67 2f 53 74 72   08Ljava/lang/Str
00a0   69 6e 67 3b 5b 4c 6a 61 76 61 2f 6c 61 6e 67 2f   ing;[Ljava/lang/
00b0   53 74 72 69 6e 67 3b 5b 4c 6a 61 76 61 2f 6c 61   String;[Ljava/la
00c0   6e 67 2f 4f 62 6a 65 63 74 3b 11 73 65 6c 65 63   ng/Object;.selec
00d0   74 53 79 73 55 73 65 72 49 6e 66 6f 71 07 5b 73   tSysUserInfoq.[s
00e0   74 72 69 6e 67 11 6a 61 76 61 2e 6c 61 6e 67 2e   tring.java.lang.
00f0   49 6e 74 65 67 65 72 71 07 5b 6f 62 6a 65 63 74   Integerq.[object
0100   c8 7b 48 04 70 61 74 68 30 28 63 6f 6d 2e 72 72   .{H.path0(com.rr
0110   68 74 2e 73 79 73 2e 73 65 72 76 69 63 65 2e 69   ht.sys.service.i
0120   6d 70 6c 2e 53 79 73 55 73 65 72 53 65 72 76 69   mpl.SysUserServi
0130   63 65 12 72 65 6d 6f 74 65 2e 61 70 70 6c 69 63   ce.remote.applic
0140   61 74 69 6f 6e 14 61 70 69 2d 67 65 6e 65 72 69   ation.api-generi
0150   63 2d 63 6f 6e 73 75 6d 65 72 09 69 6e 74 65 72   c-consumer.inter
0160   66 61 63 65 30 28 63 6f 6d 2e 72 72 68 74 2e 73   face0(com.rrht.s
0170   79 73 2e 73 65 72 76 69 63 65 2e 69 6d 70 6c 2e   ys.service.impl.
0180   53 79 73 55 73 65 72 53 65 72 76 69 63 65 07 76   SysUserService.v
0190   65 72 73 69 6f 6e 05 31 2e 32 2e 30 07 67 65 6e   ersion.1.2.0.gen
01a0   65 72 69 63 04 74 72 75 65 5a                     eric.trueZ
```

Request by Postman via APISIX dubbo-proxy (Unsuccessful):
```
0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00   ..............E.
0010   02 6b 85 ef 40 00 40 06 30 75 c0 a8 00 6c c0 a8   .k..@.@.0u...l..
0020   00 6c d3 48 1e 81 1a 75 df 65 69 4d e0 6c 80 18   .l.H...u.eiM.l..
0030   01 04 84 86 00 00 01 01 08 0a 93 33 63 26 93 33   ...........3c&.3
0040   63 26 da bb c2 00 00 00 00 00 00 00 00 02 00 00   c&..............
0050   02 27 05 32 2e 30 2e 32 30 28 63 6f 6d 2e 72 72   .'.2.0.20(com.rr
0060   68 74 2e 73 79 73 2e 73 65 72 76 69 63 65 2e 69   ht.sys.service.i
0070   6d 70 6c 2e 53 79 73 55 73 65 72 53 65 72 76 69   mpl.SysUserServi
0080   63 65 05 31 2e 32 2e 30 11 73 65 6c 65 63 74 53   ce.1.2.0.selectS
0090   79 73 55 73 65 72 49 6e 66 6f 0f 4c 6a 61 76 61   ysUserInfo.Ljava
00a0   2f 75 74 69 6c 2f 4d 61 70 3b 48 06 61 63 63 65   /util/Map;H.acce
00b0   70 74 03 2a 2f 2a 0f 61 63 63 65 70 74 2d 65 6e   pt.*/*.accept-en
00c0   63 6f 64 69 6e 67 11 67 7a 69 70 2c 20 64 65 66   coding.gzip, def
00d0   6c 61 74 65 2c 20 62 72 04 62 6f 64 79 34 d1 7b   late, br.body4.{
00e0   0a 20 20 20 20 22 73 65 72 76 69 63 65 22 3a 20   .    "service": 
00f0   22 63 6f 6d 2e 72 72 68 74 2e 63 6f 6d 6d 6f 6e   "com.rrht.common
0100   2e 73 65 72 76 69 63 65 2e 73 79 73 2e 53 79 73   .service.sys.Sys
0110   55 73 65 72 53 65 72 76 69 63 65 22 2c 0a 20 20   UserService",.  
0120   20 20 22 6d 65 74 68 6f 64 22 3a 20 22 73 65 6c     "method": "sel
0130   65 63 74 53 79 73 55 73 65 72 49 6e 66 6f 22 2c   ectSysUserInfo",
0140   0a 20 20 20 20 22 70 61 72 61 6d 65 74 65 72 73   .    "parameters
0150   22 3a 20 5b 0a 20 20 20 20 20 20 20 20 7b 0a 20   ": [.        {. 
0160   20 20 20 20 20 20 20 20 20 20 20 22 74 79 70 65              "type
0170   22 3a 20 22 6a 61 76 61 2e 6c 61 6e 67 2e 49 6e   ": "java.lang.In
0180   74 65 67 65 72 22 2c 0a 20 20 20 20 20 20 20 20   teger",.        
0190   20 20 20 20 22 76 61 6c 75 65 22 3a 20 31 0a 20       "value": 1. 
01a0   20 20 20 20 20 20 20 7d 0a 20 20 20 20 5d 0a 7d          }.    ].}
01b0   0d 63 61 63 68 65 2d 63 6f 6e 74 72 6f 6c 08 6e   .cache-control.n
01c0   6f 2d 63 61 63 68 65 0a 63 6f 6e 6e 65 63 74 69   o-cache.connecti
01d0   6f 6e 0a 6b 65 65 70 2d 61 6c 69 76 65 0e 63 6f   on.keep-alive.co
01e0   6e 74 65 6e 74 2d 6c 65 6e 67 74 68 03 32 30 39   ntent-length.209
01f0   0c 63 6f 6e 74 65 6e 74 2d 74 79 70 65 10 61 70   .content-type.ap
0200   70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 04 68   plication/json.h
0210   6f 73 74 0e 6c 6f 63 61 6c 68 6f 73 74 3a 39 30   ost.localhost:90
0220   38 30 0d 70 6f 73 74 6d 61 6e 2d 74 6f 6b 65 6e   80.postman-token
0230   30 24 39 66 64 63 34 66 32 31 2d 30 39 62 30 2d   0$9fdc4f21-09b0-
0240   34 32 66 37 2d 39 65 36 33 2d 65 31 62 63 61 36   42f7-9e63-e1bca6
0250   65 61 32 35 65 64 0a 75 73 65 72 2d 61 67 65 6e   ea25ed.user-agen
0260   74 15 50 6f 73 74 6d 61 6e 52 75 6e 74 69 6d 65   t.PostmanRuntime
0270   2f 37 2e 33 36 2e 30 5a 4e                        /7.36.0ZN
```

I will debug the issue further.

**Comment by sheharyaar** [comment] 2024-01-13 07:36
dubbo-proxy uses mod_dubbo, which at the moment does not support types other than Map<String, Object>. This has to be a feature request.
https://github.com/api7/mod_dubbo/issues/12

**Comment by sheharyaar** [comment] 2024-01-13 08:11
Reference code : https://github.com/api7/mod_dubbo/blob/4aabf9448fe4a49ca71009af8e03645ee5dadd15/ngx_http_dubbo_module.c#L694-L706

**Comment by sheharyaar** [comment] 2024-01-13 12:19
@mayunSaicmotor , let's close this issue here, and let's open a new feature-request to support data types other than Map<String, Object> in the `mod_dubbo` extension. It also lacks support for groupName and namespace parameters too. It owuld be great if you can open a new feature request for these features.

**Comment by mayunSaicmotor** [comment] 2024-01-14 13:53
do you mean changing the return  type  from Map  to Map<String, Object> will fix this issue?

**Comment by mayunSaicmotor** [comment] 2024-01-14 13:54
I will change  from Map to Map<String, Object> and test,if ok I will close. Thanks

**Comment by mayunSaicmotor** [comment] 2024-01-14 14:13
**I changed, but also failed.**
<img width="760" alt="image" src="https://github.com/apache/apisix/assets/22955377/5f60910c-e553-4534-951a-c1f25d878949">

<img width="1709" alt="image" src="https://github.com/apache/apisix/assets/22955377/c07928ee-fa05-436d-9992-c18460403676">


<img width="1709" alt="image" src="https://github.com/apache/apisix/assets/22955377/81df432a-5486-4fbd-b4f1-b183a51f5ed3">

**Comment by sheharyaar** [comment] 2024-01-14 15:06
Can you try setting hessian as serialisation protocol for Dubbo amd check

**Comment by mayunSaicmotor** [comment] 2024-01-15 03:35
I setted the hessian,but also failed. Is there anything wrong with my configuration?

<img width="1219" alt="image" src="https://github.com/apache/apisix/assets/22955377/dc653bb0-73bc-4f97-bf16-e19149b32261">

**Comment by sheharyaar** [comment] 2024-01-15 09:44
Hi @mayunSaicmotor , the datatype for your function argument in the implementation should also be `Map<string, Object>`. I was able to run your project with this change. Here is a complete order of changes :

1. `application.yml` should use hessian2 as the serialization protocol :
![image](https://github.com/apache/apisix/assets/34273345/b66f2e01-1ad1-4c7c-b455-5d631f848480)

2. Here is the interface declaration :
![image](https://github.com/apache/apisix/assets/34273345/cc75958c-be2b-4ab2-aeb7-604fb286c56e)

3. Here is the interface implementation :
![image](https://github.com/apache/apisix/assets/34273345/0b64e241-a54a-4877-a184-a010605a6fba)

**Here are a points to note :**
- The headers passed via curl/postman will be served as Map<String, Object> to the program.
- If you pass the data in header, you can directly use that using get() as in the picture, but if you pass the data via body, that data is hessian2 encoded, so you must first decode that too.

Here is the format of the received Map<String, Object> :
![image](https://github.com/apache/apisix/assets/34273345/12afe9fa-a698-479b-92fd-8e417216e265)

Here is a successful running of your program :
![image](https://github.com/apache/apisix/assets/34273345/ef3ed4a7-9b23-439b-9794-981c3945fdb6)

As you can see you will receive the response as Map<String, Object> along with the headers. (Refer : https://apisix.apache.org/docs/apisix/plugins/dubbo-proxy/#example-usage)


I think the following changes should be made to the APISIX docs :
- Support of Map<String, Object> only
- Use of serialization protocol as `hessian2`
- Passing the data in header / body (with the need to decode using hessian2)


I hope now we can close the issue. For support of other data types, please open a feature-request

**Comment by sheharyaar** [comment] 2024-01-15 09:45
For future reference, please check : https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-tengine/dubbo-samples-tengine-provider/src/main/java/org/apache/dubbo/samples/tengine/provider/DemoServiceImpl.java

**Comment by sheharyaar** [comment] 2024-01-15 13:24
Yes, I agree. It would be great if you could open a new issue, requesting the feature to help us improve dubbo-proxy plugin.

**Closed** 2024-01-15 15:44 UTC
Labels: help wanted
