### ISSUE TITLE
request help: The response head was strangely modified after passing APISIX

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4213] opened 2021-05-11 06:38 UTC
### Issue description
我通过修改本地的hosts对路由在postman上分别做了测试，一种是通过apisix，一种是直接访问后端的ip地址，结果是通过apisix后响应头被不知道什么原因的修改了，下面是不过apisix和过apisix的两种情况
![2222222](https://user-images.githubusercontent.com/31284380/117768892-9a979b00-b265-11eb-953d-8625759a664c.png)
![111111](https://user-images.githubusercontent.com/31284380/117768906-a08d7c00-b265-11eb-90bc-ee6dbcd3dd52.png)

这是后端往响应头上加头信息的代码：
![33333333333](https://user-images.githubusercontent.com/31284380/117769212-fbbf6e80-b265-11eb-855a-62376074f8d4.png)

没有开任何的插件，service配的也是穿透模式，不太明白为什么会这样。。

### Environment

* apisix version (cmd: `apisix version`):apache/apisix:2.3-alpine

**Comment by tzssangglass** [comment] 2021-05-11 06:50
adding `Server` header to the response header is a default behavior, indicating that the request is handled by APISIX， but overriding `Access-Control-Allow-Headers` is a problem, what are your upstream services?

**Comment by StretchV** [comment] 2021-05-11 06:53
upstream services is ingress-controller  ，I can get the head if I bypass APISIX and visit the upstream

**Comment by tzssangglass** [comment] 2021-05-11 06:59
> upstream services is ingress-controller ，I can get the head if I bypass APISIX and visit the upstream

what is the value of `Access-Control-Allow-Headers` in the request header?

**Comment by StretchV** [comment] 2021-05-11 07:05
这3个是用来cors跨越名访问用的， 还有我之前也有往头里加cache-control: no-cache（清除浏览器缓存）这个过完apisix后也不见了

**Comment by Firstsawyou** [comment] 2021-05-11 07:13
This information seems to be carried with the `cors` plugin enabled. You check if the `cors` plugin is enabled.
<img width="900" alt="截屏2021-05-11 下午3 09 47" src="https://user-images.githubusercontent.com/52862365/117773844-645d1a00-b26b-11eb-820b-ba4315cc6f46.png">

**Comment by StretchV** [comment] 2021-05-11 08:09
经过测试需要加上插件proxy-cache，并设置hide_cache_headers：false 才能返回给客户端，但是我不太明白为什么会这样呢，这个插件是必须要加的吗？

**Comment by Firstsawyou** [comment] 2021-05-11 08:39
The proxy-cache plugin is not necessary, you can provide route related configuration data, I will check it.

**Comment by StretchV** [comment] 2021-05-11 08:56
{
  "create_time": 1620454728,
  "update_time": 1620454728,
  "uris": [
    "/bff-message-center",
    "/bff-message-center/*"
  ],
  "name": "gateway-test_XXXXXX___bff-message-XXXXXX",
  "methods": [
    "GET",
    "HEAD",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
    "PATCH"
  ],
  "hosts": [
    "gateway-test.XXXXXX"
  ],
  "service_id": "347097464416764780",
  "enable_websocket": true,
  "status": 1
}
这是这个路由配置， service上只开了prometheus插件

**Comment by spacewander** [comment] 2021-05-11 09:06
@StretchV 
the issue is fixed by https://github.com/apache/apisix/pull/3789 in v2.5?

**Comment by StretchV** [comment] 2021-05-11 09:27
那我可以先用proxy-cache这个插件配置hide_cache_headers：false 这种方式解决吗,会有什么影响吗,我目前吧这个插件配成全局插件了,我的是2.3版本

**Comment by spacewander** [comment] 2021-05-11 09:53
> 
> 
> 那我可以先用proxy-cache这个插件配置hide_cache_headers：false 这种方式解决吗,会有什么影响吗,我目前吧这个插件配成全局插件了,我的是2.3版本

This solution looks good to me. If possible, please upgrade to 2.5.

**Comment by spacewander** [comment] 2021-05-11 09:54
Consider solved by #3789

**Closed as completed by spacewander** 2021-05-11 09:54 UTC
