### ISSUE TITLE
docs: getting-started-ip example doesn't work the api consumer request returns 404 (WSL2)

### ISSUE THREAD

**Issue by phpdave** [apache/apisix#11205] opened 2024-04-26 02:48 UTC
### Current State

The documentation on this page: https://apisix.apache.org/docs/apisix/getting-started/configure-routes/ 

states to use 
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

when i use that and then run 
```
 curl "http://127.0.0.1:9080/ip"
```

I get 
```
<html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```

### Desired State

I think the admin request should use 443 because that works

```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream" : {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:443": 1
    },
    "pass_host": "node",
    "scheme": "https"
  }
}'
```

**Comment by hanqingwu** [comment] 2024-04-28 01:23
I have try http://httpbin.org/ is working  .  https://httpbin.org is working too. 
![image](https://github.com/apache/apisix/assets/7521141/10e657d6-b86d-40be-a360-18645fa897cf)

**Comment by kayx23** [comment] 2024-04-28 02:04
I cannot reproduce either. The HTTP port with httpbin.org should work. When you create the route, did it create successfully with a 201 response code?

Sometimes the etcd nodes take a couple seconds to be ready and if you happen to be creating routes during then, the route is not created.

**Comment by phpdave** [comment] 2024-04-28 15:14
> curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
> {
>   "id": "getting-started-ip",
>   "uri": "/ip",
>   "upstream": {
>     "type": "roundrobin",
>     "nodes": {
>       "httpbin.org:80": 1
>     }
>   }
> }'

Yes direct connections to http://httpbin.org/ work but connections through APISIX with a route to httpbin.org:80 doesnt work http://127.0.0.1:9080/ip. 


> I cannot reproduce either. The HTTP port with httpbin.org should work. When you create the route, did it create successfully with a 201 response code?
> 
> Sometimes the etcd nodes take a couple seconds to be ready and if you happen to be creating routes during then, the route is not created.

I just recreated the situation using the documentation

```sh
curl -sL https://run.api7.ai/apisix/quickstart | sh
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
curl "http://127.0.0.1:9080/ip"
```
![image](https://github.com/apache/apisix/assets/5050955/bd4b2c6d-e359-42ac-9d4b-5b20b7b2295d)

**Comment by hanqingwu** [comment] 2024-04-29 01:20
![image](https://github.com/apache/apisix/assets/7521141/c30a6be4-033c-406b-adcb-9fc5eb4c9b76)
I have try your steps, but still can not reproduce.

**Comment by hanqingwu** [comment] 2024-04-29 01:20
![image](https://github.com/apache/apisix/assets/7521141/c30a6be4-033c-406b-adcb-9fc5eb4c9b76)
I have try your steps, but still can not reproduce.

**Comment by kayx23** [comment] 2024-04-29 01:34
![image](https://github.com/apache/apisix/assets/39619599/4755d7eb-a3e4-4c22-a0eb-e713408e2337)

Cannot reproduce. Any more context?

**Comment by kayx23** [comment] 2024-04-29 01:37
From your screenshot, it seems that you have gotten a 404 not found HTML page when visiting the route:

![image](https://github.com/apache/apisix/assets/39619599/7a83324b-ee77-48e9-91b8-bfd30c2f9bf9)

Not sure how this happened and this doesn't look like it's from APISIX... Because if you request a route that does not exist, the message you get should look like this:

![image](https://github.com/apache/apisix/assets/39619599/997fcf2d-6b71-4a76-85c9-067d0247c69b)

**Comment by phpdave** [comment] 2024-04-29 04:17
Maybe some oddity of WSL2 

All happens within .000075 seconds

![image](https://github.com/apache/apisix/assets/5050955/cd2919c2-51bf-449a-88fe-f871b571dfce)

**Comment by phpdave** [comment] 2024-04-29 04:17
will try it again on a Mac to see if its WSL related

**Comment by phpdave** [comment] 2024-04-29 17:49
Ok I can confirm this is an oddity of running it on Windows WSL2.  This works fine on a Mac.  Perhaps the documentation should mention WSL2 having oddities?

**Comment by kayx23** [comment] 2024-04-30 02:47
> Perhaps the documentation should mention WSL2 having oddities?

I think it should be more specific than "oddities" if this goes on doc and should be understood better. I don't have windows system and cannot investigate further. If you have any ideas, feel free to open a PR. Thanks.

**Comment by kayx23** [comment] 2024-05-11 06:25
> Perhaps the documentation should mention WSL2 having oddities?

Need someone with WSL2 environment to check and determine the next actionable item for this issue.

**Comment by kayx23** [comment] 2024-08-02 05:31
Closing this issue now as the original reporter's issue has been resolved.

As for the WSL2 oddity (not consistently reported) it can be opened as a new issue if anyone runs into it in the future.

**Closed by kayx23** 2024-08-02 05:31 UTC
Labels: good first issue, doc

**Comment by vinson-zhang** [comment] 2025-04-04 10:54
I think it's related to some built-in behavior of APISIX because, in reality, APISIX's request is not made according to the upstream configuration but based on the Host header. By default, when requesting 127.0.0.1:9080, it actually repeatedly accesses APISIX's local address, resulting in a loop and ultimately an error (also a 404). When the Host header is explicitly specified, it directly accesses the address corresponding to the Host, as shown in the screenshot below:

![Image](https://github.com/user-attachments/assets/92ac2a4c-15de-44a4-9b49-618a04f0afdd)

**Comment by vinson-zhang** [comment] 2025-04-04 11:59
I think it's related to some built-in behavior of APISIX because, in reality, APISIX's request is not made according to the upstream configuration but based on the Host header. By default, when requesting 127.0.0.1:9080, it actually repeatedly accesses APISIX's local address, resulting in a loop and ultimately an error (also a 404). When the Host header is explicitly specified, it directly accesses the address corresponding to the Host, as shown in the screenshot below:

![Image](https://github.com/user-attachments/assets/92ac2a4c-15de-44a4-9b49-618a04f0afdd)

@kayx23

**Comment by vinson-zhang** [comment] 2025-04-05 14:04
> I think it's related to some built-in behavior of APISIX because, in reality, APISIX's request is not made according to the upstream configuration but based on the Host header. By default, when requesting 127.0.0.1:9080, it actually repeatedly accesses APISIX's local address, resulting in a loop and ultimately an error (also a 404). When the Host header is explicitly specified, it directly accesses the address corresponding to the Host, as shown in the screenshot below:
> 
> ![Image](https://github.com/user-attachments/assets/92ac2a4c-15de-44a4-9b49-618a04f0afdd)
> 
> [@kayx23](https://github.com/kayx23)

@kayx23 Do you know what the root cause of this problem is?
