### ISSUE TITLE
request help: key-auth插件自定义header失败

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4228] opened 2021-05-12 10:15 UTC
### Issue description key-auth插件自定义header失败
ip如下  82是我创建route的id  请求为patch
{{ip_addr}}:9080/apisix/admin/routes/82
首先，创建一个默认的key-auth，返回成功，
{
    "plugins": {
        "key-auth": {
        }
    }
}
并且header中添加apiKey=auth-one能够成功返回响应结果
再次：通过patch创建一个自定义header的插件，返回失败
{
    "plugins": {
        "key-auth": {
            "header": "Authorization"
        }
    }
}
错误信息如下
`{
    "error_msg": "failed to check the configuration of plugin key-auth err: additional properties forbidden, found header"
}`
### Environment

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment] 2021-05-12 10:25
Duplicate of #4199

**Closed by spacewander** 2021-05-12 10:25 UTC
