### ISSUE TITLE
request help: Can network use service name instead IP?

### ISSUE THREAD

**Issue by leenux** [apache/apisix#3235] opened 2021-01-10 11:31 UTC
### Issue description
I found network use subnet 172.18.*.*
Can network use service name instead IP?
For example
```
networks:
  apisix-network:
    name: apisix-network
    driver: bridge
```
### Environment

* apisix version (cmd: `apisix version`):2.1
* OS: (cmd: `uname -a`):docker
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`):docker

**Comment by spacewander** [comment] 2021-01-11 01:11
Duplicate of https://github.com/apache/apisix-docker/issues/115

**Closed by spacewander** 2021-01-11 01:11 UTC
