### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by zhongchongan** [apache/apisix#4628] opened 2021-07-19 10:41 UTC
### Issue description
使用脚本为 APISIX 构建 OpenResty，报错：
![image](https://user-images.githubusercontent.com/87646634/126147985-739fbb62-6d6b-4367-9600-acb7a96050a8.png)
这个要怎么解决？
### Environment
centos 7.7
Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment] 2021-07-20 03:14
Duplicate of https://github.com/api7/apisix-nginx-module/issues/17

**Closed by spacewander** 2021-07-20 03:14 UTC
